name: plan

inputs:

  backend_account:
    required: true
  backend_bucket:
    required: true
  backend_region:
    required: true
  deployment_name:
    required: true
  environment:
    required: true
  oidc_principal:
    required: false # init workflow only
  state_file:
    required: true
  token:
    required: true
  var_file:
    required: false # init workflow doesn't need

runs:
  using: composite
  steps:

    - name: prepare terraform
      uses: stormreply/storm-library-for-terraform/.github/actions/terraform/prepare@main
      with:
        backend_account: ${{ inputs.backend_account }}
        backend_bucket: ${{ inputs.backend_bucket }}
        backend_region: ${{ inputs.backend_region }}
        deployment_name: ${{ inputs.deployment_name }}
        environment: ${{ inputs.environment }}
        oidc_principal: ${{ inputs.oidc_principal }}
        token: ${{ inputs.token }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init with S3 backend
      shell: bash
      run: |
        git config --list --show-origin
        terraform init \
          -backend-config="bucket=${{ inputs.backend_bucket }}" \
          -backend-config="profile=backend" \
          -backend-config="key=${{ github.repository }}/${{ inputs.state_file }}" \
          -backend-config="region=${{ inputs.backend_region }}" \
          -backend-config="use_lockfile=true"

    - name: Terraform plan
      shell: bash
      run: |
        unset AWS_SECRET_ACCESS_KEY
        unset AWS_SESSION_TOKEN
        unset AWS_ACCESS_KEY_ID

        export AWS_PROFILE=deployment
        echo "AWS_PROFILE=deployment" >> $GITHUB_ENV

        tfvars=github.tfvars
        [ -n "${{ inputs.oidc_principal }}" ] && tfvars="init.tfvars $tfvars"
        [ -n "${{ inputs.var_file}}" ] && tfvars="${{ inputs.var_file}} $tfvars"

        terraform version
        terraform plan \
          -input=false \
          -out=tfplan \
          -var-file=<(cat $tfvars) \
        && terraform show tfplan

    - name: Upload tfplan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: tfplan
