name: Prepare repository

inputs:
  environment:
    required: true
  terraform_app_id:
    required: true
  terraform_private_key:
    required: true

runs:
  using: "composite"
  steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      shell: bash
      run: echo "$GITHUB_CONTEXT"

    - name: Create Github app token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.terraform_app_id }}
        private-key: ${{ inputs.terraform_private_key }}
        owner: ${{ github.repository_owner }}

    - name: Get Storm Library catalog item
      shell: bash
      id: catalog-item
      run: |
        TOKEN=${{ steps.app-token.outputs.token }}
        curl \
          -H "Accept: application/vnd.github.raw" \
          -o catalog.yaml \
          https://x-access-token:$TOKEN@api.github.com/repos/stormreply/terraform-workflow-controller/contents/catalog.yaml
        repository=${{ github.repository }}
        repo=${repository##*/}
        yq '.catalog["'${repo}'"]' catalog.yaml > .catalog_item.yaml
        rm catalog.yaml

    - name: Create Github tfvars
      id: create-github-tfvars
      shell: bash
      run: |
        repository=${{ github.repository }}
        repo=${repository##*/}
        catalog_reference="slt-$(cat .catalog_item.yaml | yq .id)"
        name="${catalog_reference}-${repo}-${{ inputs.environment }}"
        echo "repository=${{ github.repository }}" >> $GITHUB_OUTPUT

        cat << EOF >> github.tfvars
        deployment = {
          actor       = "${{ github.actor }}"
          environment = "${{ inputs.environment }}"
          name        = "${name}"
          ref         = "${{ github.ref }}"
          ref_name    = "${{ github.ref_name }}"
          repo        = "${repo}"
          repository  = "${{ github.repository }}"
          sha         = "${{ github.sha }}"
          time        = "$(date)"
        }
        EOF
        cat github.tfvars

    - name: Set up access token
      shell: bash
      run: |
        TOKEN=${{ steps.app-token.outputs.token}}
        git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "https://github.com/"

    - name: Download providers.tf
      shell: bash
      run: |
        TOKEN=${{ steps.app-token.outputs.token }}
        curl \
          -H "Accept: application/vnd.github.raw" \
          -o providers.tf \
          https://x-access-token:$TOKEN@api.github.com/repos/stormreply/terraform-workflow-controller/contents/providers.tf

    - name: Download terraform.tf
      shell: bash
      run: |
        TOKEN=${{ steps.app-token.outputs.token }}
        curl \
          -H "Accept: application/vnd.github.raw" \
          -o terraform.tf \
          https://x-access-token:$TOKEN@api.github.com/repos/stormreply/terraform-workflow-controller/contents/terraform.tf
