name: Static Code Checks

runs:
  using: composite
  steps:

    # - name: Checkout repository
    #   uses: actions/checkout@v4

    - name: Check via pre-commit-terraform
      id: pre-commit-terraform
      shell: bash
      run: |
        # Check via pre-commit-terraform
        docker run \
          --entrypoint /bin/bash \
          -e "USERID=$(id -u):$(id -g)" \
          -v $(pwd):/lint \
          -w /lint \
          ghcr.io/antonbabenko/pre-commit-terraform:latest \
            -c "git config --list --show-origin"
