name: Static Code Checks

inputs:
  token:
    required: true

runs:
  using: composite
  steps:

    # - name: Checkout repository
    #   uses: actions/checkout@v4

    - name: Check via pre-commit-terraform
      id: pre-commit-terraform
      shell: bash
      run: |
        # Check via pre-commit-terraform
        docker run \
          --entrypoint /bin/bash \
          -e "USERID=$(id -u):$(id -g)" \
          -e "TOKEN=${{ inputs.token }}"
          -v $(pwd):/lint \
          -w /lint \
          ghcr.io/antonbabenko/pre-commit-terraform:latest \
            -c "echo $TOKEN; terraform --version; ls -la ; git config --list --show-origin; pre-commit run -a -c .pre-commit-github.yaml"
