name: Static Code Checks

inputs:
  token:
    required: true

runs:
  using: composite
  steps:

    - name: Check via pre-commit-terraform
      id: pre-commit-terraform
      shell: bash
      run: |
        # Check via pre-commit-terraform
        docker run \
          --entrypoint /bin/bash \
          -e "USERID=$(id -u):$(id -g)" \
          -e "TOKEN=${{ inputs.token }}" \
          -v $(pwd):/lint \
          -w /lint \
          ghcr.io/antonbabenko/pre-commit-terraform:latest -c '
            git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "https://github.com/"
            git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "git@github.com:"
            # git config --list --show-origin
            terraform --version
            pre-commit run -a
          '
