name: Get environment

inputs:
  json:
    required: true

runs:
  using: composite
  steps:

    - name: get-environment-from-vars
      id: get-environment-from-vars
      shell: bash
      run: |
        # get/environment-from-vars
        echo '${{ inputs.json }}' \
        | jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' \
        | tee -a $GITHUB_ENV
