name: Save backend vars

inputs:
  repository:
    required: true

runs:
  using: composite
  steps:

    - name: Set backend account
      id: set-backend-account
      uses: stormreply/storm-library-for-terraform/.github/actions/set/variable@main
      with:
        repository: ${{ inputs.repository }}
        value: ${{ inputs.backend_account }}
        variable: BACKEND_ACCOUNT

    - name: Set backend region
      id: set-backend-region
      uses: stormreply/storm-library-for-terraform/.github/actions/set/variable@main
      with:
        repository: ${{ inputs.repository }}
        value: ${{ inputs.backend_region }}
        variable: BACKEND_REGION
