name: Set deployment profile in AWS config

inputs:
  use_oidc:
    required: false
    default: "true"

runs:
  using: composite
  steps:

    - name: Assume terraform deployment role
      if: inputs.use_oidc == 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.DEPLOYMENT_REGION }}
        role-session-name: TerraformdeploymentSession
        role-to-assume: arn:aws:iam::${{ env.DEPLOYMENT_ACCOUNT }}:role/${{ env.DEPLOYMENT_ROLE }}

    - name: Configure terraform deployment role
      shell: bash
      run: |
        aws configure set profile.deployment.region ${{ env.DEPLOYMENT_REGION }}
        aws configure set profile.deployment.aws_access_key_id $(echo ${AWS_ACCESS_KEY_ID})
        aws configure set profile.deployment.aws_secret_access_key $(echo ${AWS_SECRET_ACCESS_KEY})
        aws configure set profile.deployment.aws_session_token $(echo ${AWS_SESSION_TOKEN})
