name: Get basic setup

inputs:

  backend_account:
    required: true
  environment:
    required: false
  private_access_token:
    required: false
  terraform_app_id:
    required: false
  terraform_private_key:
    required: false


outputs:
  backend_bucket:
    description: Central administration backend bucket
    value: ${{ steps.get-backend-bucket.outputs.backend_bucket }}
  deployment_name:
    description: Name of our deployment
    value: ${{ steps.get-deployment-name.outputs.name }}
  state_file:
    description: Terraform State file we are gonna use
    value: ${{ steps.get-state-file.outputs.state_file }}
  token:
    description: Token to use for GitHub calls
    value: ${{ steps.get-token.outputs.token}}

runs:
  using: composite
  steps:

    - name: Create Github app token
      id: create-github-app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        owner: ${{ github.repository_owner }}

    # TODO: move
    - name: Get Token
      id: get-token
      shell: bash
      env:
        APP_TOKEN: ${{ steps.create-github-app-token.outputs.token }}
      run: |
        # Get token
        token=${APP_TOKEN}
        [ -z "${token}" ] && token=${{ inputs.private_access_token }}
        echo "token=${token}" >> $GITHUB_OUTPUT

    - name: Get backend bucket
      id: get-backend-bucket
      uses: stormreply/storm-library-for-terraform/.github/actions/get/backend-bucket@main
      with:
        backend_account: ${{ inputs.backend_account }}

    - name: Get deployment name
      id: get-deployment-name
      uses: stormreply/storm-library-for-terraform/.github/actions/get/deployment-name@main
      with:
        environment: ${{ inputs.environment }}
        token: ${{ steps.get-token.outputs.token}}

    - name: Get state file
      id: get-state-file
      uses: stormreply/storm-library-for-terraform/.github/actions/get/state-file@main
      with:
        deployment_name: ${{ steps.get-deployment-name.outputs.name }}
