name: Unregister deployment

inputs:
  account_id:
    required: true
  environment:
    required: true
  region:
    required: true

runs:
  using: composite
  steps:
    - name: Unregister expiry
      shell: bash
      run: |
        # TODO: find way to configure/identify buucket name, most prob from gh vars
        account_id=${{ inputs.account_id }}
        region=${{ inputs.region }}
        repository=${{ github.repository }}
        repo=${repository##*/}
        deployment="storm-${repo}-${{ inputs.environment }}"

        expiries=$(
          aws s3api list-objects-v2 \
            --bucket storm-library-for-terraform-123456789012 \
            --prefix schedule \
            --query 'Contents[].Key'
        )

        [ "${expiries}" != "null" ] && expiries=$(echo "${expiries}" | jq -r ".[]") || expiries=""

        expiries=$(echo "${expiries}" | grep "${account_id}-${region}-${deployment}") || true

        if [ -n "$expiries" ] ; then
          echo "$expiries"
        else
          echo "NO EXPIRIES"
        fi

        for expiry in $expiries ; do
          aws s3 rm s3://storm-library-for-terraform-123456789012/schedule/${expiry}  # TODO: take bucket name from vars
          echo "UNREGISTERED ${expiry}"
        done