name: Unregister deployment

inputs:
  account_id:
    required: true
  environment:
    required: true
  region:
    required: true

runs:
  using: "composite"
  steps:
    - name: Unregister expiry
      shell: bash
      run: |
        account_id=${{ inputs.account_id }}
        region=${{ inputs.region }}
        repository=${{ github.repository }}
        repo=${repository##*/}
        deployment="storm-${repo}-${{ inputs.environment }}"

        expiries=$(
          aws s3api list-objects-v2 \
            --bucket storm-github-terraform-backend \
            --prefix expiries \
            --query 'Contents[].Key'
        )

        [ "${expiries}" != "null" ] && expiries=$(echo "${expiries}" | jq -r ".[]") || expiries=""

        expiries=$(echo "${expiries}" | grep "${account_id}-${region}-${deployment}")

        echo "$expiries"

        for expiry in $expiries ; do
          aws s3 rm s3://storm-github-terraform-backend/${expiry}  # TODO: take bucket name from vars
        done