name: Unregister deployment

inputs:
  account_id:
    required: true
  environment:
    required: true
  region:
    required: true

runs:
  using: composite
  steps:

    - name: Get bucket name
      id: get-bucket-name
      uses: stormreply/terraform-workflow-controller/.github/actions/get-bucket-name@main
      with:
        account_id: ${{ inputs.account_id }}

    - name: Unregister expiry
      shell: bash
      run: |
        account_id=${{ inputs.account_id }}
        region=${{ inputs.region }}
        repository=${{ github.repository }}
        repo=${repository##*/}
        deployment="storm-${repo}-${{ inputs.environment }}"

        timestamps=$(
          aws s3api list-objects-v2 \
            --bucket ${{ steps.get-bucket-name.outputs.bucket }} \
            --prefix schedule \
            --query 'Contents[].Key'
        )

        [ "${timestamps}" != "null" ] && timestamps=$(echo "${timestamps}" | jq -r ".[]") || timestamps=""

        timestamps=$(echo "${timestamps}" | grep "${account_id}-${region}-${deployment}") || true

        if [ -n "$timestamps" ] ; then
          echo "$timestamps"
        else
          echo "NO timestamps"
        fi

        for expiry in $timestamps ; do
          aws s3 rm s3://${{ steps.get-bucket-name.outputs.bucket }}/schedule/${expiry}
          echo "UNREGISTERED ${expiry}"
        done