name: Unregister deployment

inputs:
  account_id:
    required: true
  backend_bucket:
    required: true
  deployment_name:
    required: true
  deployment_region:
    required: true

runs:
  using: composite
  steps:

    - name: Unregister expiry
      shell: bash
      run: |
        account_id=${{ inputs.account_id }}
        backend_bucket=${{ inputs.backend_bucket }}
        deployment_name="${{ inputs.deployment_name }}"
        deployment_region=${{ inputs.deployment_region }}

        timestamps=$(
          aws s3api list-objects-v2 \
            --bucket ${backend_bucket} \
            --prefix schedule \
            --query 'Contents[].Key'
        )

        [ "${timestamps}" != "null" ] && timestamps=$(echo "${timestamps}" | jq -r ".[]") || timestamps=""

        timestamps=$(echo "${timestamps}" | grep "${account_id}-${deployment_region}-${deployment_name}") || true

        if [ -n "$timestamps" ] ; then
          echo "$timestamps"
        else
          echo "NO timestamps"
        fi

        for key in $timestamps ; do
          aws s3 rm s3://${backend_bucket}/${key}
          echo "UNREGISTERED ${key}"
        done
