name: Unregister deployment

inputs:
  account_id:
    required: true
  environment:
    required: true
  expires_after:
    required: true
  region:
    required: true

runs:
  using: "composite"
  steps:
    - name: Unregister expiry
      shell: bash
      run: |
        account_id=${{ inputs.account_id }}
        repository=${{ github.repository }}
        repo=${repository##*/}
        deployment="storm-${repo}-${{ inputs.environment }}"

        expiry=$(date -d "now + ${{ inputs.expires_after}}" +"%Y%m%d-%H%M%S")
        expiry_file="${expiry}-${account_id}-${region}-${deployment}"
        aws s3 rm s3://storm-github-terraform-backend/expiries/${expiry_file}  # TODO: take bucket name from vars