name: Unschedule actions

inputs:
  action:
    required: true

runs:
  using: composite
  steps:

    - name: Unschedule actions
      shell: bash
      run: |
        # scheduler/unschedule

        action=${{ inputs.action }}

        deployment_account=${{ env.DEPLOYMENT_ACCOUNT }}
        backend_bucket=${{ env.BACKEND_BUCKET }}
        deployment_name=${{ env.DEPLOYMENT_NAME }}
        deployment_region=${{ env.DEPLOYMENT_REGION }}

        timestamps=$(
          aws s3api list-objects-v2 \
            --bucket ${backend_bucket} \
            --prefix schedule \
            --query 'Contents[].Key'
        )

        [ "${timestamps}" != "null" ] && timestamps=$(echo "${timestamps}" | jq -r ".[]") || timestamps=""

        pattern="${action}-${deployment_account}-${deployment_region}-${deployment_name}"

        if [ -n "$timestamps" ] ; then
          for key in $timestamps ; do
            if echo "$key" | grep -E "$pattern" > /dev/null ; then
              echo -n "REMOVE $key... "
              aws s3 rm s3://${backend_bucket}/${key} > /dev/null
              echo DONE
            else
              echo "SKIP   $key"
            fi
          done
        else
          echo "NO timestamps"
        fi
