name: Unschedule actions

inputs:
  account_id:
    required: true
  action:
    required: true
    default: ".*"
  backend_bucket:
    required: true
  deployment_name:
    required: true
  deployment_region:
    required: true

runs:
  using: composite
  steps:

    - name: Unschedule actions
      shell: bash
      run: |
        # Unschedule actions
        action=${{ inputs.action }}

        account_id=${{ inputs.account_id }}
        backend_bucket=${{ inputs.backend_bucket }}
        deployment_name="${{ inputs.deployment_name }}"
        deployment_region=${{ inputs.deployment_region }}

        timestamps=$(
          aws s3api list-objects-v2 \
            --bucket ${backend_bucket} \
            --prefix schedule \
            --query 'Contents[].Key'
        )

        [ "${timestamps}" != "null" ] && timestamps=$(echo "${timestamps}" | jq -r ".[]") || timestamps=""

        pattern="${action}-${account_id}-${deployment_region}-${deployment_name}"

        if [ -n "$timestamps" ] ; then
          for key in $timestamps ; do
            if echo "$key" | grep -E "$pattern" > /dev/null ] ; then
              echo -n "REMOVE $key... "
              aws s3 rm s3://${backend_bucket}/${key}
              echo DONE
            else
              echo "SKIP   $key"
            fi
          done
        else
          echo "NO timestamps"
        fi
