name: Set github.tfvars

inputs:
  deployment_name:
    required: true
  environment:
    required: true

runs:
  using: composite
  steps:

    - name: Set github.tfvars
      shell: bash
      run: |
        # set/github-tfvars
        repository=${{ github.repository }}
        repo=${repository##*/}
        deployment_name=${{ inputs.deployment_name }}

        [ -n "${{ inputs.environment }}" ] \
        && environment="${{ inputs.environment }}" \
        || environment="${{ github.actor }}"

        cat << EOF >> github.tfvars
        deployment = {
          actor       = "${{ github.actor }}"
          environment = "${environment}"
          name        = "${deployment_name}"
          ref         = "${{ github.ref }}"
          ref_name    = "${{ github.ref_name }}"
          repo        = "${repo}"
          repository  = "${{ github.repository }}"
          sha         = "${{ github.sha }}"
          time        = "$(date)"
        }
        EOF
        echo "github.tfvars"
        cat github.tfvars
