name: Download File

inputs:
  file:
    required: true

runs:
  using: composite
  steps:
    - name: download file
      id: download-file
      shell: bash
      run: |
        # download ${{ inputs.file }}

        api="x-access-token:${{ env.TOKEN }}@api.github.com"
        path="repos/stormreply/storm-library-for-terraform/contents"
        file=${{ inputs.file }}

        output=$(
          curl \
            -o "${file}" \
            -H "Accept: application/vnd.github.raw" \
            "https://${api}/${path}/${file}" \
          2> /dev/null
        )

        # cat $file

        # TODO: countercheck/unify with get/deployment-name
        # TODO: check content if containing error status
