name: Download File

inputs:
  file:
    required: true
  token:
    required: true

runs:
  using: composite
  steps:
    - name: download File
      id: download-file
      shell: bash
      run: |
        # download ${{ inputs.file }}
        api="x-access-token:${{ inputs.token }}@api.github.com"
        path="repos/stormreply/storm-library-for-terraform/contents"
        file=${{ inputs.file }}

        output=$(curl \
          -o "${file}" \
          -H "Accept: application/vnd.github.raw" \
          "https://${api}/${path}/${file}"
        > /dev/null 2&>1
        )

        cat $file
        
        # TODO: countercheck/unify with get/deployment-name
        # TODO: check content if containing error status
