name: Get repository variable

inputs:
  pass_if_set:
    required: false
    default: ""
  repository:
    required: true
  token:
    required: true
  variable:
    required: true

outputs:
  value:
    description: Value of the variable requested
    value: ${{ steps.get-repo-var.outputs.value }}

runs:
  using: composite
  steps:
    - name: Get repository variable via API
      shell: bash
      id: get-repo-var
      env:
        TOKEN: ${{ inputs.token }}
        VARIABLE: ${{ inputs.variable }}
        REPO: ${{ inputs.repository }}
      run: |
        variable="${{ inputs.pass_if_set }}"
        if [ "${variable}" == "" ] ; then
          variable=$(
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$REPO/actions/variables/$VARIABLE
          )
          value=$(echo ${variable} | jq -r .value)
        fi
        echo "value=${value}"
        echo "value=${value}" >> $GITHUB_OUTPUT