name: Set Github Principal

inputs:
  github_principal:
    required: true

runs:
  using: composite
  steps:

    - name: Set Github Principal
      shell: bash
      run: |
        # Set Github Principal ${{ inputs.github_principal }}
        github_principal = ${{ inputs.github_principal }}
        [ -z "$github_principal" ] && github_principal=${{ github.repository_owner }}
        cat << EOF >> oidc.tfvars
        github_principal = "${github_principal}"
        EOF

        echo "github_principal=${github_principal}"
        echo "github_principal=${github_principal}" >> $GITHUB_OUTPUT
