name: AWS configure
inputs:
  account_id:
    required: true
  region:
    required: true
  backend_role:
    required: false
  deployment_role:
    required: false

runs:
  using: composite
  steps:

