name: Single sign on

inputs:
  access_domain:
    required: true
  backend_region:
    required: false

outputs:
  access_token:
    value:  ${{ steps.sso.outputs.ACCESS_TOKEN }}

runs:
  using: composite
  steps:

    - name: Check AWS CLI version
      shell: bash
      run: aws --version

    - name: aws sso login
      shell: bash
      id: sso
      run: |
        # oidc/single-sign-on

        cd ${{ github.action_path }}
        mkdir -p ${HOME}/.aws

        cat << EOF >> ${HOME}/.aws/config
        [profile default]
        sso_region=${{ inputs.backend_region }}
        sso_start_url=https://${{ inputs.access_domain }}.awsapps.com/start/#
        EOF

        aws sso login --no-browser > login-output.txt &
        pid=$!
        while [ ! -f login-output.txt ]; do
          sleep 1
        done
        cat << EOF

        Click the link below:


        EOF
        i=0
        cat login-output.txt | grep "?user_code="
        while [ -n "$(ps -p ${pid} -o pid=)" ]; do
          cat login-output.txt | grep "?user_code=" || true
          echo -ne .
          # i=$((i + 1))
          sleep 5
        done
        # echo
        # # echo -ne "remaining seconds: "
        # while [ -n "$(ps -p ${pid} -o pid=)" ]; do
        #   echo -ne . && true
        #   i=$((i+1))
        #   sleep 1
        # done
        # [ $i -eq 0 ] && exit 1

        export "ACCESS_TOKEN=$(jq -r '. | select(.accessToken != null) | .accessToken' ${HOME}/.aws/sso/cache/*.json)"
        echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_OUTPUT
