name: Get bucket name

inputs:
  backend_account:
    required: true

outputs:
  backend_bucket:
    description: Central administration backend bucket
    value: ${{ steps.get-backend-bucket.outputs.backend_bucket }}

runs:
  using: composite
  steps:
    - name: Get backend bucket
      id: get-backend-bucket
      shell: bash
      run: |
        # Get backend bucket
        backend_bucket="storm-library-for-terraform-${{ inputs.backend_account }}"
        echo "backend_bucket=${backend_bucket}"
        echo "backend_bucket=${backend_bucket}" >> $GITHUB_OUTPUT
