name: Set deployment profile in AWS config

inputs:
  deployment_account:
    required: true
  deployment_region:
    required: true
  deployment_role:
    required: false
  use_oidc:
    required: false
    default: "true"

runs:
  using: composite
  steps:

    - name: Assume terraform deployment role
      if: inputs.use_oidc == 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.deployment_region }}
        role-session-name: TerraformdeploymentSession
        role-to-assume: arn:aws:iam::${{ inputs.deployment_account }}:role/${{ inputs.deployment_role }}

    - name: Configure terraform deployment role
      shell: bash
      run: |
        aws configure set profile.deployment.region ${{ inputs.deployment_region }}
        aws configure set profile.deployment.aws_access_key_id $(echo ${AWS_ACCESS_KEY_ID})
        aws configure set profile.deployment.aws_secret_access_key $(echo ${AWS_SECRET_ACCESS_KEY})
        aws configure set profile.deployment.aws_session_token $(echo ${AWS_SESSION_TOKEN})
