name: Get token

inputs:

  private_access_token:
    required: false
  terraform_app_id:
    required: false
  terraform_private_key:
    required: false


outputs:
  token:
    description: Token to use for GitHub calls
    value: ${{ steps.get-token.outputs.token}}

runs:
  using: composite
  steps:

    - name: Create Github app token
      if: inputs.terraform_app_id != '' && inputs.terraform_app_id != 'NONE'
      id: create-github-app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.terraform_app_id }}
        private-key: ${{ inputs.terraform_private_key }}
        owner: ${{ github.repository_owner }}

    - name: Get Token
      id: get-token
      shell: bash
      run: |
        # get/token
        type="Github App Token" # so far
        token="${{ steps.create-github-app-token.outputs.token }}"
        if [ -z "${token}" ] ; then
          token=${{ inputs.private_access_token }}
          type="Personal Access Token"
        fi
        echo "::notice ::using your $type as token"
        if [ ${#token} -eq 0 ] ; then
          echo "::error title=No valid token::could not get a token"
          exit 1
        else
          echo "token=${token}" >> $GITHUB_OUTPUT
        fi
