name: Terraform destroy

runs:
  using: composite
  steps:

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init with S3 backend
      shell: bash
      run: |
        terraform init \
          -backend-config="bucket=${{ env.BACKEND_BUCKET }}" \
          -backend-config="profile=backend" \
          -backend-config="key=${{ github.repository }}/${{ env.STATE_FILE }}" \
          -backend-config="region=${{ env.BACKEND_REGION }}" \
          -backend-config="use_lockfile=true"

    - name: Terraform destroy
      shell: bash
      run: |
        unset AWS_SECRET_ACCESS_KEY
        unset AWS_SESSION_TOKEN
        unset AWS_ACCESS_KEY_ID

        export AWS_PROFILE=deployment
        echo "AWS_PROFILE=deployment" >> $GITHUB_ENV

        # [ -n "${{ inputs.var_file }}" ] && var_file="-var-file=${{ inputs.var_file }}"

        terraform version
        terraform destroy \
          -auto-approve \
          -input=false
