name: Single sign on

inputs:
  access_domain:
    required: true
    default: storm-unity
  region:
    required: false
    default: eu-central-1
outputs:
  access_token:
    value:  ${{ steps.sso.outputs.ACCESS_TOKEN }}

runs:
  using: composite
  steps:

    - name: Check AWS CLI version
      shell: bash
      run: aws --version

    - name: aws sso login
      shell: bash
      id: sso
      run: |

        cd ${{ github.action_path }}
        mkdir -p ${HOME}/.aws

        cat << EOF >> ${HOME}/.aws/config
        [profile default]
        sso_region=${{ inputs.region }}
        sso_start_url=https://${{ inputs.access_domain }}.awsapps.com/start/#
        EOF

        aws sso login --no-browser > login-output.txt &
        pid=$!
        while [ ! -f login-output.txt ]; do
          sleep 1
        done
        while [ -n "$(ps -p ${pid} -o pid=)" ]; do
          cat login-output.txt | grep "?user_code=" || true
          sleep 5
        done

        export "ACCESS_TOKEN=$(jq -r '. | select(.accessToken != null) | .accessToken' ${HOME}/.aws/sso/cache/*.json)"
        echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_OUTPUT
