name: Setup roles

inputs:
  account_id:
    required: true
  region:
    required: true

runs:
  using: composite
  steps:

    - name: Assume gh-terraform-backend-role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{inputs.region}}
        role-session-name: GitHubBackendSession
        role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/gh-terraform-backend-role

    - name: Configure gh-terraform-backend-role
      shell: bash
      run: |
        aws configure set profile.backend.region ${{ inputs.region }}
        aws configure set profile.backend.aws_access_key_id $(echo ${AWS_ACCESS_KEY_ID})
        aws configure set profile.backend.aws_secret_access_key $(echo ${AWS_SECRET_ACCESS_KEY})
        aws configure set profile.backend.aws_session_token $(echo ${AWS_SESSION_TOKEN})

    - name: Assume gh-oidc-deployment-role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.region }}
        role-session-name: GitHubOIDCSession
        role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/gh-oidc-deployment-role

    - name: Configure gh-oidc-deployment-role
      shell: bash
      run: |
        aws configure set profile.oidc.region ${{ inputs.region }}
        aws configure set profile.oidc.aws_access_key_id $(echo ${AWS_ACCESS_KEY_ID})
        aws configure set profile.oidc.aws_secret_access_key $(echo ${AWS_SECRET_ACCESS_KEY})
        aws configure set profile.oidc.aws_session_token $(echo ${AWS_SESSION_TOKEN})
