name: Schedule action

inputs:
  account_id:
    required: true
  action:
    required: true
  backend_bucket:
    required: true
  deployment_name:
    required: true
  deployment_region:
    required: true
  environment:
    required: false
  lifetime:
    required: false
  wait:
    required: true

runs:
  using: composite
  steps:

    - name: Unschedule actions
      uses: stormreply/storm-library-for-terraform/.github/actions/scheduler/unschedule@main
      with:
        account_id: ${{ inputs.account_id }}
        backend_bucket: ${{ inputs.backend_bucket }}
        deployment_name: ${{ inputs.deployment_name }}
        deployment_region: ${{ inputs.deployment_region }}
      continue-on-error: true

    - name: Schedule action
      shell: bash
      run: |
        # Schedule action
        action=${{ inputs.action }}

        account_id=${{ inputs.account_id }}
        backend_bucket=${{ inputs.backend_bucket }}
        deployment_name="${{ inputs.deployment_name }}"
        deployment_region=${{ inputs.deployment_region }}
        environment=${{ inputs.environment || github.actor }}
        lifetime="${{ inputs.lifetime }}"
        wait="${{ inputs.wait }}"

        time=$(date -d "now + ${wait}" +"%Y%m%d-%H%M%S")
        timestamp="${time}-${action}-${account_id}-${deployment_region}-${deployment_name}"

        cat << EOF | grep -v ': "null"' | yq -o=json >> ${timestamp}
        environment: "$environment"
        lifetime: "$lifetime"
        EOF

        echo -n "SCHEDULE ${timestamp}... "
        aws s3 cp ${timestamp} s3://${backend_bucket}/schedule/ > /dev/null
        echo DONE
