name: Schedule action

inputs:
  action:
    required: true
  lifetime:
    required: false
  delay:
    required: true

runs:
  using: composite
  steps:

    - name: Unschedule actions
      uses: stormreply/storm-library-for-terraform/.github/actions/scheduler/unschedule@main
      with:
        action: ".*"
      continue-on-error: true

    - name: Schedule action
      shell: bash
      run: |
        # scheduler/schedule
        backend_bucket=${{ env.BACKEND_BUCKET }}
        datetime=$(date -d "now + ${delay}" +"%Y%m%d%H%M%S")

        date="${datetime:0:8}"
        time="${datetime:8:6}"
        action=${{ inputs.action }}
        account_id=${{ env.DEPLOYMENT_ACCOUNT }}
        region=${{ env.DEPLOYMENT_REGION }}
        repo="${{ env.REPO }}"
        environment=${{ env.ENVIRONMENT || github.actor }}

        lifetime="${{ inputs.lifetime }}"
        delay="${{ inputs.delay }}"

        job="${date}.${time}.${action}.${account_id}.${region}.${repo}.${environment}"

        cat << EOF | grep -E -v ': "(null|)"' | yq -o=json >> ${job}
        environment: "$environment"
        lifetime: "$lifetime"
        EOF

        echo -n "SCHEDULE ${job}... "
        aws s3 cp "$job" s3://${backend_bucket}/schedule/ > /dev/null
        echo DONE
