name: Schedule action

inputs:
  account_id:
    required: true
  action:
    required: true
  backend_bucket:
    required: true
  wait:
    required: true
  deployment_name:
    required: true
  deployment_region:
    required: true
  lifetime:
    required: false

runs:
  using: composite
  steps:

    - name: Unschedule actions
      uses: stormreply/storm-library-for-terraform/.github/actions/scheduler/unschedule@main
      with:
        account_id: ${{ inputs.account_id }}
        backend_bucket: ${{ inputs.backend_bucket }}
        deployment_name: ${{ inputs.deployment_name }}
        deployment_region: ${{ inputs.deployment_region }}
      continue-on-error: true

    - name: Schedule action
      shell: bash
      run: |
        # Schedule action
        action=${{ inputs.action }}

        account_id=${{ inputs.account_id }}
        backend_bucket=${{ inputs.backend_bucket }}
        wait="${{ inputs.wait }}"
        deployment_name="${{ inputs.deployment_name }}"
        deployment_region=${{ inputs.deployment_region }}
        lifetime="${{ inputs.lifetime }}"

        time=$(date -d "now + ${wait}" +"%Y%m%d-%H%M%S")
        timestamp="${time}-${action}-${account_id}-${deployment_region}-${deployment_name}"

        cat << EOF | yq -o=json >> ${timestamp}
        account_id: "$account_id"
        action: "$action"
        wait: "$wait"
        backend_bucket: "$backend_bucket"
        deployment_name: "$deployment_name"
        deployment_region: "$deployment_region"
        lifetime: "$lifetime"
        EOF

        echo -n "SCHEDULE ${timestamp}... "
        aws s3 cp ${timestamp} s3://${backend_bucket}/schedule/ > /dev/null
        echo DONE
