name: Schedule action

inputs:
  action:
    required: true
  lifetime:
    required: false
  delay:
    required: true

runs:
  using: composite
  steps:

    - name: Unschedule actions
      uses: stormreply/storm-library-for-terraform/.github/actions/scheduler/unschedule@main
      with:
        action: ".*"
      continue-on-error: true

    - name: Schedule action
      shell: bash
      run: |
        # scheduler/schedule
        action=${{ inputs.action }}

        deployment_account=${{ env.DEPLOYMENT_ACCOUNT }}
        backend_bucket=${{ env.BACKEND_BUCKET }}
        deployment_name="${{ env.DEPLOYMENT_NAME }}"
        deployment_region=${{ env.DEPLOYMENT_REGION }}
        environment=${{ env.ENVIRONMENT || github.actor }}
        lifetime="${{ inputs.lifetime }}"
        delay="${{ inputs.delay }}"

        time=$(date -d "now + ${delay}" +"%Y%m%d-%H%M%S")
        timestamp="${time}-${action}-${deployment_account}-${deployment_region}-${deployment_name}"

        cat << EOF | grep -E -v ': "(null|)"' | yq -o=json >> ${timestamp}
        environment: "$environment"
        lifetime: "$lifetime"
        EOF

        echo -n "SCHEDULE ${timestamp}... "
        aws s3 cp ${timestamp} s3://${backend_bucket}/schedule/ > /dev/null
        echo DONE
