name: Set AWS profiles

inputs:
  use_oidc:
    required: true

runs:
  using: composite
  steps:

    - name: Set backend profile in AWS config
      uses: stormreply/storm-library-for-terraform/.github/actions/set/aws/profiles/backend@main
      with:
        backend_role: slt-0-storm-library-for-terraform-backend
        use_oidc: ${{ inputs.use_oidc }}

    - name: Set deployment profile in AWS config
      uses: stormreply/storm-library-for-terraform/.github/actions/set/aws/profiles/deployment@main
      with:
        deployment_role: slt-0-storm-library-for-terraform-deployment
        use_oidc: ${{ inputs.use_oidc }}
