name: Get bucket name

inputs:
  account_id:
    required: true

outputs:
  bucket:
    description: Central administration bucket
    value: ${{ steps.get-bucket-name.outputs.bucket }}

runs:
  using: composite
  steps:
    - name: Get bucket name
      id: get-bucket-name
      shell: bash
      run: |
        bucket="storm-library-for-terraform-${{ inputs.account_id }}"
        echo "bucket=${bucket}"
        echo "bucket=${bucket}" >> $GITHUB_OUTPUT
