name: Terraform apply

inputs:
  region:
    required: true
  tfvars:
    required: true
  tf_state_file:
    required: true

runs:
  using: composite
  steps:

    - name: Download tfplan
      uses: actions/download-artifact@v4
      with:
        name: tfplan

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init with S3 backend
      shell: bash
      run: |
        # TODO: bootstrap repo and retrieve bucket from vars
        terraform init \
          -backend-config="bucket=storm-github-terraform-backend" \
          -backend-config="profile=backend" \
          -backend-config="key=${{ github.repository }}/${{ inputs.tf_state_file }}" \
          -backend-config="region=${{ inputs.region }}" \
          -backend-config="use_lockfile=true"

    - name: Terraform apply
      shell: bash
      run: |
        unset AWS_SECRET_ACCESS_KEY
        unset AWS_SESSION_TOKEN
        unset AWS_ACCESS_KEY_ID

        export AWS_PROFILE=oidc
        echo "AWS_PROFILE=oidc" >> $GITHUB_ENV

        terraform version
        terraform apply \
          -input=false \
          -auto-approve \
          tfplan
