name: Terraform apply

inputs:
  backend_bucket:
    required: true
  backend_region:
    required: true
  state_file:
    required: true
  var_file:
    required: true

runs:
  using: composite
  steps:

    - name: Download tfplan
      uses: actions/download-artifact@v4
      with:
        name: tfplan

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init with S3 backend
      shell: bash
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.backend_bucket }}" \
          -backend-config="profile=backend" \
          -backend-config="key=${{ github.repository }}/${{ inputs.state_file }}" \
          -backend-config="region=${{ inputs.backend_region }}" \
          -backend-config="use_lockfile=true"

    - name: Terraform apply
      shell: bash
      run: |
        unset AWS_SECRET_ACCESS_KEY
        unset AWS_SESSION_TOKEN
        unset AWS_ACCESS_KEY_ID

        export AWS_PROFILE=deployment
        echo "AWS_PROFILE=deployment" >> $GITHUB_ENV

        terraform version
        terraform apply \
          -input=false \
          -auto-approve \
          tfplan
