name: Schedule action

inputs:
  account_id:
    required: true
  action:
    required: true
  after:
    required: true
  backend_bucket:
    required: true
  deployment_name:
    required: true
  deployment_region:
    required: true

runs:
  using: composite
  steps:

    - name: Unschedule action
      uses: stormreply/storm-library-for-terraform/.github/actions/unschedule@main
      with:
        account_id: ${{ inputs.account_id }}
        backend_bucket: ${{ inputs.backend_bucket }}
        deployment_name: ${{ inputs.deployment_name }}
        deployment_region: ${{ inputs.deployment_region }}
      continue-on-error: true

    - name: Schedule action
      shell: bash
      run: |
        account_id=${{ inputs.account_id }}
        action=${{ inputs.action }}
        backend_bucket=${{ inputs.backend_bucket }}
        deployment_name="${{ inputs.deployment_name }}"
        deployment_region=${{ inputs.deployment_region }}

        time=$(date -d "now + ${{ inputs.after}}" +"%Y%m%d-%H%M%S")
        timestamp="${time}-${action}-${account_id}-${deployment_region}-${deployment_name}"
        touch ${timestamp}
        aws s3 cp ${timestamp} s3://${backend_bucket}/schedule/
        echo "SCHEDULED ${timestamp}"
