name: plan

inputs:

  var_file:
    required: false

runs:
  using: composite
  steps:

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init with S3 backend
      shell: bash
      run: |
        git config --list --show-origin
        terraform init \
          -backend-config="bucket=${{ env.BACKEND_BUCKET }}" \
          -backend-config="profile=backend" \
          -backend-config="key=${{ github.repository }}/${{ env.STATE_FILE }}" \
          -backend-config="region=${{ env.BACKEND_REGION }}" \
          -backend-config="use_lockfile=true"

    - name: Terraform plan
      shell: bash
      run: |
        unset AWS_SECRET_ACCESS_KEY
        unset AWS_SESSION_TOKEN
        unset AWS_ACCESS_KEY_ID

        export AWS_PROFILE=deployment
        echo "AWS_PROFILE=deployment" >> $GITHUB_ENV

        [ -f _metadata.tfvars ] && var_files="-var-file=_metadata.tfvars"
        [ -n "${{ inputs.var_file }}" ] && var_files="$var_file -var-file=${{ inputs.var_file }}"

        terraform version
        terraform plan \
          -input=false \
          -out=tfplan \
          $var_files \
        && terraform show tfplan

    - name: Upload tfplan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: tfplan
