jobs:
  set-variable:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      # optional, wenn du andere scopes brauchst

    steps:
      - name: Set Repository Variable via API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAR_NAME: MY_VARIABLE
          VAR_VALUE: my_value
          REPO: ${{ github.repository }}
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/actions/variables/$VAR_NAME \
            -d "{\"name\":\"$VAR_NAME\", \"value\":\"$VAR_VALUE\"}" \
            -f || \
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/actions/variables \
            -d "{\"name\":\"$VAR_NAME\", \"value\":\"$VAR_VALUE\"}"
