name: Save account id

inputs:
  account_id:
    required: true
  repository:
    required: true
  token:
    required: true

runs:
  using: composite
  steps:
    - name: Set Repository Variable via API
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        VAR_NAME: STORM_LIBRARY_BUILD_ACCOUNT_ID
        VAR_VALUE: ${{ inputs.account_id }}
        REPO: ${{ inputs.repository }}
      run: |
        curl -X PATCH \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/$REPO/actions/variables/$VAR_NAME \
          -d "{\"name\":\"$VAR_NAME\", \"value\":\"$VAR_VALUE\"}" \
          -f || \
        curl -X POST \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/$REPO/actions/variables \
          -d "{\"name\":\"$VAR_NAME\", \"value\":\"$VAR_VALUE\"}"
        echo "Saved account_id ${{ inputs.account_id }} to vars.STORM_LIBRARY_BUILD_ACCOUNT_ID"

    # permissions:
    #   actions: write
    #   contents: read
    #   # optional, wenn du andere scopes brauchst
