name: Save deployment vars

inputs:
  repository:
    required: true

runs:
  using: composite
  steps:

    - name: Set deployment account
      id: set-deployment-account
      uses: stormreply/storm-library-for-terraform/.github/actions/set/variable@main
      with:
        repository: ${{ inputs.repository }}
        value: ${{ env.DEPLOYMENT_ACCOUNT }}
        variable: DEPLOYMENT_ACCOUNT

    - name: Set deployment region
      id: set-deployment-region
      uses: stormreply/storm-library-for-terraform/.github/actions/set/variable@main
      with:
        repository: ${{ inputs.repository }}
        value: ${{ env.DEPLOYMENT_REGION }}
        variable: DEPLOYMENT_REGION
