name: Get Configuration

runs:
  using: composite
  steps:
    - name: Get Configuration
      id: get-configuration
      shell: bash
      run: |
        backend_account=${{ env.BACKEND_ACCOUNT }}
        backend_region=${{ env.BACKEND_REGION}}

        echo "backend account: ${backend_account}"
        echo "backend region:  ${backend_region}"
