name: Get Configuration

inputs:
  backend_account:
    required: true
  backend_region:
    required: true
  deployment_account:
    required: true
  deployment_region:
    required: true
  private_access_token:
    required: true
  terraform_app_id:
    required: true
  terraform_private_key:
    required: true


runs:
  using: composite
  steps:
    - name: Get Configuration
      id: get-configuration
      shell: bash
      run: |
        echo "backend account:       ${{ inputs.backend_account }}"
        echo "backend region:        ${{ inputs.backend_region }}"
        echo "deployment account:    ${{ inputs.deployment_account }}"
        echo "deployment region:     ${{ inputs.deployment_region }}"
        echo "private access token:  ${{ inputs.private_access_token }}"
        echo "terraform app id:      ${{ inputs.terraform_app_id }}"
        echo "terraform private key: ${{ inputs.terraform_private_key }}"
