name: Get Configuration

inputs:
  backend_account:
    required: true
  backend_region:
    required: true
  deployment_account:
    required: true
  deployment_region:
    required: true

runs:
  using: composite
  steps:
    - name: Get Configuration
      id: get-configuration
      shell: bash
      run: |
        echo "backend account: ${{ inputs.backend_account }}"
        echo "backend region:  ${{ inputs.backend_region }}"
