name: Get Configuration

runs:
  using: composite
  steps:
    - name: Dump all context
      run: echo '${{ toJson(vars) }}'

    - name: Get Configuration
      id: get-configuration
      shell: bash
      env:
        backend_account: ${{ vars.BACKEND_ACCOUNT }}
        backend_region: ${{ vars.BACKEND_REGION }}
      run: |
        echo "backend account: ${backend_account}"
        echo "backend region:  ${backend_region}"
