name: Set repository variable

inputs:
  repository:
    required: true
  token:
    required: true
  value:
    required: true
  variable:
    required: true

runs:
  using: composite
  steps:
    - name: Set repository variable via API
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        VARIABLE: ${{ inputs.variable }}
        VALUE: ${{ inputs.value }}
        REPO: ${{ inputs.repository }}
      run: |
        curl -X PATCH \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/$REPO/actions/variables/$VARIABLE \
          -d "{\"name\":\"$VARIABLE\", \"value\":\"$VALUE\"}" \
          -f \
        2> /dev/null \
        || \
        curl -X POST \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/$REPO/actions/variables \
          -d "{\"name\":\"$VARIABLE\", \"value\":\"$VALUE\"}" \
        2> /dev/null
        echo "Saved account_id ${{ inputs.account_id }} to vars.${VARIABLE} in $REPO"
