name: Select

runs:
  using: composite
  steps:

    - name: Select
      shell: bash
      run: |
        # scheduler/select

        now=$(date -d now +"%s")

        echo "CURRENT TIME:   $(date -d now +"%Y-%m-%d %H:%M:%S")"

        timestamps=$(
          aws s3api list-objects-v2 \
            --bucket ${{ env.BACKEND_BUCKET }} \
            --prefix schedule \
            --query 'Contents[].Key'
        )

        [ "${timestamps}" != "null" ] && timestamps=$(echo "${timestamps}" | jq -r ".[]") || timestamps=""

        # object name must start with datestamp. if none does, continue (true)
        timestamps=$(echo "$timestamps" | grep -E "/[0-9]{8}-") || true

        if [ -n "$timestamps" ] ; then
          rm -f /tmp/selected 2>&1
          touch /tmp/selected
        else
          echo "No timestamps found."
        fi

        for e in $timestamps ; do

          file=${e##*/} ; f=${file}
          date=${f%%-*} ; f=${f##$date-}
          time=${f%%-*} ; f=${f##$time-}

          time="${time:0:2}:${time:2:2}:${time:4:2}"
          when=$(date -d "${date} ${time}" +"%s")

          if [ ${when} -lt ${now} ] ; then
            echo "SELECT $file"
            echo "$file" >> /tmp/selected
          else
            echo "SKIP   $file"
          fi

          [ -f /tmp/selected ] && has_selected="true" || has_selected="false"

          echo "has_selected=$has_selected" | tee -a $GITHUB_OUTPUT

        done
