name: Select

runs:
  using: composite
  steps:

    - name: select
      shell: bash
      run: |
        # scheduler/select

        now=$(date -d now +"%s")

        echo "TIME   $(date -d now +"%Y%m%d.%H%M%S")"

        jobs=$(
          aws s3api list-objects-v2 \
            --bucket ${{ env.BACKEND_BUCKET }} \
            --prefix schedule \
            --query 'Contents[].Key'
        )

        [ "${jobs}" != "null" ] && jobs=$(echo "${jobs}" | jq -r ".[]") || jobs=""

        # object name must start with timestamp. if none does, continue (true)
        jobs=$(echo "$jobs" | grep -E "/[0-9]{8}.[0-9]{6}") || true

        if [ -n "$jobs" ] ; then
          rm -f /tmp/selected 2>&1
          touch /tmp/selected
        else
          echo "no jobs to schedule."
        fi

        for job in $jobs ; do

          file=${job##*/} ; f=${file}
          date=${f%%.*} ; f=${f##$date.}
          time=${f%%.*} ; f=${f##$time.}

          time="${time:0:2}:${time:2:2}:${time:4:2}"
          when=$(date -d "${date} ${time}" +"%s")

          if [ ${when} -lt ${now} ] ; then
            echo "SELECT $file"
            echo "$file" >> /tmp/selected
          else
            echo "SKIP   $file"
          fi

          [ -f /tmp/selected ] && has_selected="true" || has_selected="false"

          # echo "has_selected=$has_selected" >> $GITHUB_OUTPUT
          echo "has_selected=$has_selected" >> $GITHUB_ENV

        done
