name: Get access token

inputs:
  access_domain:
    required: true
  backend_region:
    required: false

outputs:
  access_token:
    value:  ${{ steps.get-access-token.outputs.ACCESS_TOKEN }}

runs:
  using: composite
  steps:

    - name: get access token
      shell: bash
      id: get-access-token
      run: |
        # get/access-token

        cd ${{ github.action_path }}
        mkdir -p ${HOME}/.aws

        cat << EOF >> ${HOME}/.aws/config
        [profile default]
        sso_region=${{ inputs.backend_region }}
        sso_start_url=https://${{ inputs.access_domain }}.awsapps.com/start/#
        EOF

        aws sso login --no-browser > login-output.txt &
        pid=$!
        while [ ! -f login-output.txt ]; do
          sleep 1
        done
        cat << EOF
        Click the link below:
        EOF
        while [ -n "$(ps -p ${pid} -o pid=)" ]; do
          cat login-output.txt | grep "?user_code=" || true
          sleep 5
        done
        export "ACCESS_TOKEN=$(jq -r '. | select(.accessToken != null) | .accessToken' ${HOME}/.aws/sso/cache/*.json)"
        echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_OUTPUT
