name: Destroy

runs:
  using: composite
  steps:

      - name: checkout code
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout@main

      - name: terraform destroy
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/destroy@main
