name: Batch destroy

inputs:
  backend_bucket:
    required: true

runs:
  using: composite
  steps:

    - name: Run destroy
      shell: bash
      run: |

        timestamps=$(
          aws s3api list-objects-v2 \
            --bucket ${{ inputs.backend_bucket }} \
            --prefix schedule \
            --query 'Contents[].Key'
        )

        [ "${timestamps}" != "null" ] && timestamps=$(echo "${timestamps}" | jq -r ".[]") || timestamps=""

        # object name must start with datestamp. if none does, continue (true)
        timestamps=$(echo "$timestamps" | grep -E "/[0-9]{8}-") || true

        [ -z "$timestamps" ] && echo "No timestamps found."

        for e in $timestamps ; do

          file=${e##*/} ; f=${file}
          date=${f%%-*} ; f=${f##$date-}
          time=${f%%-*} ; f=${f##$time-}
          account_id=${f%%-*} ; f=${f##$account_id-}
          region=${f%-${f#*-*-*-}} ; f=${f##$region-}
          slt=${f%%-*} ; f=${f##$slt-}
          catalog_id=${f%%-*} ; f=${f##$catalog_id-}
          repo=${f%-*}
          environment=${f##$repo-}
          time="${time:0:2}:${time:2:2}:${time:4:2}"
          expiry=$(date -d "${date} ${time}" +"%s")
          now=$(date -d now +"%s")
          nows=$(date -d now +"%Y%m%d-%H%M%S")
          echo -n "checking current time (${nows}) against ${file}... "

          if [ ${expiry} -lt ${now} ] ; then
            echo "EXPIRED"
            # TODO: handle "stormreply"
            gh workflow run destroy.yaml \
              --repo stormreply/${repo} \
              -f environment=${environment} &
          else
            echo "AUTHORIZED"
          fi

        done
