name: Create _metadata.tfvars

runs:
  using: composite
  steps:

    - name: create _metadata.tfvars
      shell: bash
      run: |
        # checkout/create-metadata-tfvars

        catalog_id=${{ env.CATALOG_ID }}
        deployment_name=${{ env.DEPLOYMENT_NAME }}
        repository=${{ github.repository }}
        repo=${repository##*/}
        short_name=${{ env.SHORT_NAME }}

        environment=${${{ env.ENVIRONMENT }}:-${{ github.actor }}}

        cat << EOF > _metadata.tfvars
        _metadata = {
          actor       = "${{ github.actor }}"
          catalog_id  = "${catalog_id}"
          deployment  = "${deployment_name}"
          environment = "${environment}"
          ref         = "${{ github.ref }}"
          ref_name    = "${{ github.ref_name }}"
          repo        = "${repo}"
          repository  = "${{ github.repository }}"
          sha         = "${{ github.sha }}"
          short_name  = "${short_name}"
          time        = "$(date)"
        }
        EOF

        echo "_metadata.tfvars"
        cat _metadata.tfvars