name: Checkout Code

inputs:

  backend_account:
    required: true
  backend_region:
    required: true
  deployment_name:
    required: true
  environment:
    required: true
  token:
    required: true
  use_oidc:
    required: false
    default: true

# TODO: rename prepare into terraform/checkout and maybe move set-aws-profiles out of it

runs:
  using: composite
  steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    # NOTE: important to position *behind* checkout
    - name: Git config rewrite URLs
      shell: bash
      run: |
        # Git config rewrite URLs
        TOKEN=${{ inputs.token }}
        git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "https://github.com/"
        # git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "git@github.com:"

        # TODO: show only in debug mode
        # echo "global .gitconfig:"
        # cat ~/.gitconfig
        # echo "local .git/config:"
        # cat .git/config
      # TODO: move into action

    - name: Download providers.tf
      uses: stormreply/storm-library-for-terraform/.github/actions/download@main
      with:
        token: ${{ inputs.token }}
        file: providers.tf

    - name: set deployment-tags
      uses: stormreply/storm-library-for-terraform/.github/actions/set/deployment-tags@main
      with:
        deployment_name: ${{ inputs.deployment_name }}
        environment: ${{ inputs.environment }}

    # TODO: check if can be moved to plan, apply, destroy
    - name: Set AWS profiles
      uses: stormreply/storm-library-for-terraform/.github/actions/set/aws/profiles@main
      with:
        backend_account: ${{ inputs.backend_account }}
        backend_region: ${{ inputs.backend_region }}
        backend_role: slt-0-storm-library-for-terraform-backend
        deployment_account: ${{ inputs.backend_account }}
        deployment_region: ${{ inputs.backend_region }}
        deployment_role: slt-0-storm-library-for-terraform-deployment
        use_oidc: ${{ inputs.use_oidc }}
