name: Checkout Code

inputs:

  init: # have we been called from the init workflow?
    type: boolean
    required: false
    default: false

# TODO: maybe move set-aws-profiles somewhere else

runs:
  using: composite
  steps:

    - name: checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ env.TOKEN }}

    - name: rewrite URLs
      uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout/rewrite-urls@main

    # TODO: rethink
    # - name: download providers.tf
    #   uses: stormreply/storm-library-for-terraform/.github/actions/download@main
    #   with:
    #     file: providers.tf

    - name: create deployment-tags
      uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout/create-deployment-tags@main

    - name: create backend.tf
      uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout/create-backend@main

    - name: create metadata.tfvars
      uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout/create-metadata-tfvars@main

    - name: create init.tfvars
      if: inputs.init == 'true'
      uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout/create-init-tfvars@main

    - name: Set backend profile in AWS config
      uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout/set-backend-profile@main
      with:
        use_oidc: ${{ inputs.init != 'true' }} # use oidc if we are not in the init workflow

    - name: Set deployment profile in AWS config
      uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout/set-deployment-profile@main
      with:
        use_oidc: ${{ inputs.init != 'true' }} # use oidc if we are not in the init workflow
