name: Checkout Code

inputs:

  init: # have we been called from the init workflow?
    type: boolean
    required: false
    default: false

# TODO: maybe move set-aws-profiles somewhere else

runs:
  using: composite
  steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ env.TOKEN }}

    # NOTE: important to position *behind* checkout
    - name: Git config rewrite URLs
      shell: bash
      run: |
        # Git config rewrite URLs
        TOKEN=${{ env.TOKEN }}
        git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "https://github.com/"
        # git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "git@github.com:"

        # TODO: show only in debug mode
        # echo "global .gitconfig:"
        # cat ~/.gitconfig
        # echo "local .git/config:"
        # cat .git/config
      # TODO: move into action

    - name: Download providers.tf
      uses: stormreply/storm-library-for-terraform/.github/actions/download@main
      with:
        token: ${{ env.TOKEN }}
        file: providers.tf

    - name: set deployment-tags
      uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout/deployment-tags@main
      with:
        deployment_name: ${{ env.DEPLOYMENT_NAME }}
        environment: ${{ env.ENVIRONMENT }}

    - name: set init.tfvars
      if: inputs.init == 'true'
      uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout/init-tfvars@main

    # TODO: check if can be moved to plan, apply, destroy
    - name: Set AWS profiles
      uses: stormreply/storm-library-for-terraform/.github/actions/set/aws/profiles@main
      with:
        use_oidc: ${{ inputs.init != 'true' }} # use oidc if we are not in the init workflow
