name: Terraform plan

inputs:
  bucket:
    required: true
  region:
    required: true
  state_file:
    required: true
  var_file:
    required: true

runs:
  using: composite
  steps:

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init with S3 backend
      shell: bash
      run: |
        git config --list --show-origin
        terraform init \
          -backend-config="bucket=${{ inputs.bucket }}" \
          -backend-config="profile=backend" \
          -backend-config="key=${{ github.repository }}/${{ inputs.state_file }}" \
          -backend-config="region=${{ inputs.region }}" \
          -backend-config="use_lockfile=true"

    - name: Terraform plan
      shell: bash
      run: |
        unset AWS_SECRET_ACCESS_KEY
        unset AWS_SESSION_TOKEN
        unset AWS_ACCESS_KEY_ID

        export AWS_PROFILE=deployment
        echo "AWS_PROFILE=deployment" >> $GITHUB_ENV

        tfvars=github.tfvars
        [ -n "${{ inputs.var_file}}" ] && tfvars="${{ inputs.var_file}} $tfvars"

        terraform version
        terraform plan \
          -input=false \
          -out=tfplan \
          -var-file=<(cat $tfvars) \
        && terraform show tfplan

    - name: Upload tfplan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: tfplan