name: Get deployment name

inputs:
  environment:
    required: true
  token:
    required: true

outputs:
  name:
    value: ${{ steps.get-deployment-name.outputs.deployment_name }}

runs:
  using: composite
  steps:
    - name: Get deployment name
      id: get-deployment-name
      shell: bash
      run: |
        # get/deployment-name
        TOKEN=${{ inputs.token }}
        output=$(
          curl \
            -H "Accept: application/vnd.github.raw" \
            -o catalog.yaml \
            https://x-access-token:$TOKEN@api.github.com/repos/stormreply/storm-library-for-terraform/contents/catalog.yaml \
            2> /dev/null
        )
        echo "$output"
        echo "---"
        cat catalog.yaml
        status=$(echo "$output" | jq '( .status // empty )')
        # status is "" or HTTP error code
        if [ -n "$status" ] ; then
          echo "$output"
          echo "::error ::status from set variable call is $status"
          exit 1
        fi

        repository=${{ github.repository }}
        repo=${repository##*/}

        yq '.catalog["'${repo}'"]' catalog.yaml > catalog_item.yaml
        catalog_id=$(cat catalog_item.yaml | yq .id)
        echo "SLT catalog id for $repo: $catalog_id"
        catalog_reference="slt-${catalog_id}"
        rm catalog.yaml

        deployment_name="${catalog_reference}-${repo}"

        if [ "${catalog_id}" != "0" ] ; then
          [ -n "${{ inputs.environment }}" ] \
          && environment="${{ inputs.environment }}" \
          || environment="${{ github.actor }}"
          deployment_name="${deployment_name}-${environment}"
        fi

        echo "deployment_name=${deployment_name}" >> $GITHUB_OUTPUT
        echo "name=${deployment_name}" >> $GITHUB_OUTPUT