name: Get deployment name

inputs:
  environment:
    required: true
  token:
    required: true

outputs:
  name:
    value: ${{ steps.get-deployment-name.outputs.deployment_name }}

runs:
  using: composite
  steps:
    - name: Get deployment name
      id: get-deployment-name
      shell: bash
      run: |
        # get/deployment-name

        api="x-access-token:${{ inputs.token }}@api.github.com"
        path="repos/stormreply/storm-library-for-terraform/contents"
        file=catalog.yaml

        output=$(
          curl \
            -o "${file}" \
            -H "Accept: application/vnd.github.raw" \
            "https://${api}/${path}/${file}" \
          2> /dev/null
        )

        status=$(
          cat catalog.yaml | jq '( .status // empty )' 2> /dev/null \
          || true
        ) # "|| true" is for jq can't parse - as it ought to be yaml
        # status is "" or HTTP error code
        if [ -n "$status" ] ; then
          cat catalog.yaml
          echo "::error ::status from download call is $status"
          exit 1
        fi

        repository=${{ github.repository }}
        repo=${repository##*/}

        yq '.catalog["'${repo}'"]' catalog.yaml > catalog_item.yaml
        catalog_id=$(cat catalog_item.yaml | yq .id)
        [ "$catalog_id" = "null" ] \
          && echo "::error ::${repo} or its id are not known to the catalog" \
          && exit 1
        echo "SLT catalog id for $repo: $catalog_id"
        catalog_reference="slt-${catalog_id}"
        rm catalog.yaml

        deployment_name="${catalog_reference}-${repo}"

        if [ "${catalog_id}" != "0" ] ; then
          [ -n "${{ inputs.environment }}" ] \
          && environment="${{ inputs.environment }}" \
          || environment="${{ github.actor }}"
          deployment_name="${deployment_name}-${environment}"
        fi

        echo "deployment_name=${deployment_name}" >> $GITHUB_OUTPUT
        echo "name=${deployment_name}" >> $GITHUB_OUTPUT