name: Set environment vars

inputs:
  private_access_token:
    required: false
  terraform_private_key:
    required: false
  yaml:
    required: true

# outputs:
#   access_domain:
#     value: ${{ steps.get-vars.outputs.access_domain }}
#   access_role:
#     value: ${{ steps.get-vars.outputs.access_role }}
#   backend_account:
#     value: ${{ steps.get-vars.outputs.backend_account }}
#   backend_bucket:
#     value: ${{ steps.get-backend-bucket.outputs.backend_bucket }}
#   backend_region:
#     value: ${{ steps.get-vars.outputs.backend_region }}
#   deployment_account:
#     value: ${{ steps.get-vars.outputs.backend_account }}
#   deployment_name:
#     value: ${{ steps.get-deployment-name.outputs.name }}
#   deployment_region:
#     value: ${{ steps.get-vars.outputs.backend_region }}
#   environment:
#     value: ${{ steps.get-vars.outputs.environment }}
#   oidc_principal:
#     value: ${{ steps.get-vars.outputs.oidc_principal }}
#   state_file:
#     value: ${{ steps.get-state-file.outputs.state_file }}
#   token:
#     value: ${{ steps.get-token.outputs.token }}

runs:
  using: composite
  steps:

    - name: set env vars from input
      id: set-env-vars-from-input
      uses: stormreply/storm-library-for-terraform/.github/actions/set/env-vars-from-input@main
      with:
        yaml: ${{ inputs.yaml }}

    - name: set env vars from others
      id: set-env-vars-from-others
      uses: stormreply/storm-library-for-terraform/.github/actions/set/env-vars-from-others@main
      with:
        private_access_token: ${{ inputs.private_access_token }}
        terraform_private_key: ${{ inputs.terraform_private_key }}

    - name: show environment vars
      id: show-vars
      shell: bash
      run: |
        # show-vars

        pat="${{ inputs.private_access_token }}"
        tpk="${{ inputs.terraform_private_key }}"

        echo "access domain:         $ACCESS_DOMAIN"
        echo "access role:           $ACCESS_ROLE"
        echo "backend account:       $BACKEND_ACCOUNT"
        echo "backend region:        $BACKEND_REGION"
        echo "deployment account:    $BACKEND_ACCOUNT"
        echo "deployment region:     $BACKEND_REGION"
        echo "environment:           $ENVIRONMENT"
        echo "oidc principal:        $OIDC_PRINCIPAL"
        echo "terraform app id:      $TERRAFORM_APP_ID"
        echo
        echo "backend bucket:        $BACKEND_BUCKET"
        echo "deployment name:       $DEPLOYMENT_NAME"
        echo "state file:            $STATE_FILE"
        echo
        echo "private access token length:  ${#pat}"
        echo "terraform private key length: ${#tpk}"
        echo
        echo "token length: ${#TOKEN}"
