name: Get deployment name

inputs:
  environment:
    required: true

outputs:
  name:
    value: ${{ steps.get-deployment-name.outputs.name }}

runs:
  using: composite
  steps:
    - name: Get deployment name
      id: get-deployment-name
      shell: bash
      run: |
        repository=${{ github.repository }}
        repo=${repository##*/}

        catalog_id=$(cat catalog_item.yaml | yq .id)
        catalog_reference="slt-${catalog_id}"

        deployment_name="${catalog_reference}-${repo}"

        if [ "${catalog_id}" != "0" ] ; then
          [ -n "${{ inputs.environment }}" ] \
          && suffix="${{ inputs.environment }}" \
          || suffix="${{ github.actor }}"
          deployment_name="${deployment_name}-${suffix}"
        fi

        echo "deployment name: ${deployment_name}"
        echo "name=${deployment_name}" >> $GITHUB_OUTPUT
