name: Prepare

inputs:

  backend_account:
    required: true
  backend_region:
    required: true
  environment:
    required: false
  private_access_token:
    required: false
  terraform_app_id:
    required: false
  terraform_private_key:
    required: false
  use_oidc:
    required: false
    default: "true"

outputs:
  backend_bucket:
    description: Central administration backend bucket
    value: ${{ steps.setup.outputs.backend_bucket }}
  deployment_name:
    description: Name of this deployment
    value: ${{ steps.setup.outputs.deployment_name}}
  state_file:
    description: Name of the state file
    value: ${{ steps.setup.outputs.state_file }}
  token:
    description: Token to use for GitHub calls
    value: ${{ steps.setup.outputs.token}}

runs:
  using: composite
  steps:

    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   shell: bash
    #   run: echo "$GITHUB_CONTEXT"

    - name: Time
      shell: bash
      run: date

    - name: Show current Configuration
      id: show-current-configuration
      uses: stormreply/storm-library-for-terraform/.github/actions/get/configuration@main
      with:
        access_domain: ${{ vars.ACCESS_DOMAIN }}
        access_role: ${{vars.ACCESS_ROLE}}
        backend_account: ${{ vars.BACKEND_ACCOUNT }}
        backend_region: ${{ vars.BACKEND_REGION }}
        deployment_account: ${{ vars.DEPLOYMENT_ACCOUNT }}
        deployment_region: ${{ vars.DEPLOYMENT_REGION }}
        private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
        terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
        terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

    - name: Setup
      id: setup
      uses: stormreply/storm-library-for-terraform/.github/actions/setup@main
      with:
        backend_account: ${{ inputs.backend_account }}
        environment: ${{ inputs.environment }}
        private_access_token: ${{ inputs.private_access_token }}
        terraform_app_id: ${{ inputs.terraform_app_id }}
        terraform_private_key: ${{ inputs.terraform_private_key }}

    - name: Checkout repository
      uses: actions/checkout@v4

    # NOTE: position *behind* checkout
    - name: Git config rewrite URLs
      shell: bash
      run: |
        # Git config rewrite URLs
        TOKEN=${{ steps.setup.outputs.token }}
        git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "https://github.com/"
        # git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "git@github.com:"

    - name: Show git configs
      shell: bash
      run: |
        # Show git configs
        echo "global .gitconfig:"
        cat ~/.gitconfig
        echo "local .git/config:"
        cat .git/config

    - name: Download providers.tf
      uses: stormreply/storm-library-for-terraform/.github/actions/download@main
      with:
        token: ${{ steps.setup.outputs.token }}
        file: providers.tf

    - name: Set deployment tags
      uses: stormreply/storm-library-for-terraform/.github/actions/set/deployment-tags@main
      with:
        deployment_name: ${{ steps.setup.outputs.deployment_name }}
        environment: ${{ inputs.environment }}

    - name: Set backend profile in AWS config
      uses: stormreply/storm-library-for-terraform/.github/actions/set/backend-profile@main
      with:
        backend_account: ${{ inputs.backend_account }}
        backend_region: ${{ inputs.backend_region }}
        backend_role: slt-0-storm-library-for-terraform-backend
        use_oidc: ${{ inputs.use_oidc }}

    - name: Set deployment profile in AWS config
      uses: stormreply/storm-library-for-terraform/.github/actions/set/deployment-profile@main
      with:
        deployment_account: ${{ inputs.backend_account }} # TODO:
        deployment_region: ${{ inputs.backend_region }} # TODO:
        deployment_role: slt-0-storm-library-for-terraform-deployment
        use_oidc: ${{ inputs.use_oidc }}
