name: Prepare

inputs:

  backend_account:
    required: true
  backend_region:
    required: true
  deployment_name:
    required: true
  environment:
    required: true
  token:
    required: true
  use_oidc:
    required: false
    default: "true"

runs:
  using: composite
  steps:

    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   shell: bash
    #   run: echo "$GITHUB_CONTEXT"

    - name: Time
      shell: bash
      run: date

    - name: Checkout repository
      uses: actions/checkout@v4

    # NOTE: position *behind* checkout
    - name: Git config rewrite URLs
      shell: bash
      run: |
        # Git config rewrite URLs
        TOKEN=${{ inputs.token }}
        git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "https://github.com/"
        # git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "git@github.com:"

        echo "global .gitconfig:"
        cat ~/.gitconfig
        echo "local .git/config:"
        cat .git/config

    - name: Download providers.tf
      uses: stormreply/storm-library-for-terraform/.github/actions/download@main
      with:
        token: ${{ inputs.token }}
        file: providers.tf

    - name: Set deployment tags
      uses: stormreply/storm-library-for-terraform/.github/actions/set/deployment-tags@main
      with:
        deployment_name: ${{ inputs.deployment_name }}
        environment: ${{ inputs.environment }}

    - name: Set AWS profiles
      uses: stormreply/storm-library-for-terraform/.github/actions/set/aws/profiles@main
      with:
        backend_account: ${{ inputs.backend_account }}
        backend_region: ${{ inputs.backend_region }}
        backend_role: slt-0-storm-library-for-terraform-backend
        deployment_account: ${{ inputs.backend_account }} # TODO:
        deployment_region: ${{ inputs.backend_region }} # TODO:
        deployment_role: slt-0-storm-library-for-terraform-deployment
        use_oidc: ${{ inputs.use_oidc }}
