name: Prepare

inputs:

  backend_account:
    required: true
  backend_region:
    required: true
  environment:
    required: false
  private_access_token:
    required: false
  terraform_app_id:
    required: false
  terraform_private_key:
    required: false
  use_oidc:
    required: false
    default: "true"

outputs:
  backend_bucket:
    description: Central administration backend bucket
    value: ${{ steps.get-backend-bucket.outputs.backend_bucket }}
  backend_region:
    value: ${{ inputs.backend_region }}
  deployment_name:
    description: Name of this deployment
    value: ${{ steps.get-deployment-name.outputs.name}}
  state_file:
    description: Name of the state file
    value: ${{ steps.get-state-file.outputs.state_file }}
  token:
    description: Token to use for GitHub calls
    value: ${{ steps.get-token.outputs.token}}

runs:
  using: composite
  steps:

    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   shell: bash
    #   run: echo "$GITHUB_CONTEXT"

    - name: Time
      shell: bash
      run: date

    - name: Get Token
      id: get-token
      uses: stormreply/storm-library-for-terraform/.github/actions/get/token@main
      with:
        private_access_token: ${{ inputs.private_access_token }}
        terraform_app_id: ${{ inputs.terraform_app_id }}
        terraform_private_key: ${{ inputs.terraform_private_key }}

    - name: Get backend bucket
      id: get-backend-bucket
      uses: stormreply/storm-library-for-terraform/.github/actions/get/backend-bucket@main
      with:
        backend_account: ${{ inputs.backend_account }}

    - name: Get deployment name
      id: get-deployment-name
      uses: stormreply/storm-library-for-terraform/.github/actions/get/deployment-name@main
      with:
        environment: ${{ inputs.environment }}
        token: ${{ steps.get-token.outputs.token}}

    - name: Get state file
      id: get-state-file
      uses: stormreply/storm-library-for-terraform/.github/actions/get/state-file@main
      with:
        deployment_name: ${{ steps.get-deployment-name.outputs.name }}

    - name: Checkout repository
      uses: actions/checkout@v4

    # NOTE: position *behind* checkout
    - name: Git config rewrite URLs
      shell: bash
      run: |
        # Git config rewrite URLs
        TOKEN=${{ steps.get-token.outputs.token }}
        git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "https://github.com/"
        # git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "git@github.com:"

        echo "global .gitconfig:"
        cat ~/.gitconfig
        echo "local .git/config:"
        cat .git/config

    - name: Download providers.tf
      uses: stormreply/storm-library-for-terraform/.github/actions/download@main
      with:
        token: ${{ steps.get-token.outputs.token }}
        file: providers.tf

    - name: Set deployment tags
      uses: stormreply/storm-library-for-terraform/.github/actions/set/deployment-tags@main
      with:
        deployment_name: ${{ steps.get-deployment-name.outputs.name }}
        environment: ${{ inputs.environment }}

    - name: Set backend profile in AWS config
      uses: stormreply/storm-library-for-terraform/.github/actions/set/backend-profile@main
      with:
        backend_account: ${{ inputs.backend_account }}
        backend_region: ${{ inputs.backend_region }}
        backend_role: slt-0-storm-library-for-terraform-backend
        use_oidc: ${{ inputs.use_oidc }}

    - name: Set deployment profile in AWS config
      uses: stormreply/storm-library-for-terraform/.github/actions/set/deployment-profile@main
      with:
        deployment_account: ${{ inputs.backend_account }} # TODO:
        deployment_region: ${{ inputs.backend_region }} # TODO:
        deployment_role: slt-0-storm-library-for-terraform-deployment
        use_oidc: ${{ inputs.use_oidc }}
