name: Prepare

inputs:

  terraform_app_id:
    required: true
  terraform_private_key:
    required: true

  account_id:
    required: false
  environment:
    required: false
  backend_region:
    required: false
  use_oidc:
    required: false
    default: "true"

outputs:
  account_id:
    description: Id of the AWS account we are deploying to
    value: ${{ steps.setup.outputs.account_id }}
  app_token:
    description: App token for GitHub API access
    value: ${{ steps.setup.outputs.token }}
  backend_bucket:
    description: Central administration backend bucket
    value: ${{ steps.setup.outputs.backend_bucket }}
  backend_region:
    description: Central administration backend region
    value: ${{ steps.setup.outputs.backend_region }}
  deployment_name:
    description: Name of this deployment
    value: ${{ steps.setup.outputs.deployment_name}}
  deployment_region:
    description: Region resources are being deployed to
    value: ${{ steps.setup.outputs.deployment_region }}
  state_file:
    description: Name of the state file
    value: ${{ steps.setup.outputs.state_file }}

runs:
  using: composite
  steps:

    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   shell: bash
    #   run: echo "$GITHUB_CONTEXT"

    - name: Time
      shell: bash
      run: date

    - name: Setup
      id: setup
      uses: stormreply/storm-library-for-terraform/.github/actions/setup@main
      with:
        account_id: ${{ inputs.account_id }}
        app_id: ${{ inputs.terraform_app_id }}
        environment: ${{ inputs.environment }}
        private_key: ${{ inputs.terraform_private_key }}

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up access token
      shell: bash
      run: |
        TOKEN=${{ steps.setup.outputs.token}}
        git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "https://github.com/"

    - name: Download providers.tf
      uses: stormreply/storm-library-for-terraform/.github/actions/download@main
      with:
        token: ${{ steps.setup.outputs.token }}
        file: providers.tf

    - name: Download terraform.tf
      uses: stormreply/storm-library-for-terraform/.github/actions/download@main
      with:
        token: ${{ steps.setup.outputs.token }}
        file: terraform.tf

    - name: Create deployment variables
      shell: bash
      run: |
        repository=${{ github.repository }}
        repo=${repository##*/}
        deployment_name=${{ steps.setup.outputs.deployment_name }}

        cat << EOF >> github.tfvars
        deployment = {
          actor       = "${{ github.actor }}"
          environment = "${{ inputs.environment }}"
          name        = "${deployment_name}"
          ref         = "${{ github.ref }}"
          ref_name    = "${{ github.ref_name }}"
          repo        = "${repo}"
          repository  = "${{ github.repository }}"
          sha         = "${{ github.sha }}"
          time        = "$(date)"
        }
        EOF

        cat github.tfvars

    - name: Set backend profile in AWS config
      uses: stormreply/storm-library-for-terraform/.github/actions/set/backend-profile@main
      with:
        account_id: ${{ steps.setup.outputs.account_id }}
        backend_region: ${{ steps.setup.outputs.backend_region }}
        backend_role: slt-0-storm-library-for-terraform-backend
        use_oidc: ${{ inputs.use_oidc }}

    - name: Set deployment profile in AWS config
      uses: stormreply/storm-library-for-terraform/.github/actions/set/deployment-profile@main
      with:
        account_id: ${{ steps.setup.outputs.account_id }}
        deployment_region: ${{ steps.setup.outputs.deployment_region }}
        deployment_role: slt-0-storm-library-for-terraform-deployment
        use_oidc: ${{ inputs.use_oidc }}
