name: Prepare

inputs:
  # TODO: prepare needs account_id and region for (auto-)destroy. if set, pass them through
  environment:
    required: false
  terraform_app_id:
    required: true
  terraform_private_key:
    required: true
  use_oidc:
    required: false
    default: "true"

outputs:
  account_id:
    description: Id of the AWS account we are deploying to
    value: ${{ steps.get-account-id.outputs.value }}
  app_token:
    description: App token for GitHub API access
    value: ${{ steps.app-token.outputs.token }}
  bucket:
    description: Central administration bucket
    value: ${{ steps.get-bucket-name.outputs.bucket }}
  region:
    description: AWS region we are deploying to
    value: ${{ steps.get-region.outputs.value }}
  state_file:
    description: Name of the state file
    value: ${{ steps.get-state-file.outputs.state_file }}

runs:
  using: composite
  steps:

    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   shell: bash
    #   run: echo "$GITHUB_CONTEXT"

    - name: Time
      shell: bash
      run: date

    - name: Create Github app token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.terraform_app_id }}
        private-key: ${{ inputs.terraform_private_key }}
        owner: ${{ github.repository_owner }}

    - name: Get account id
      id: get-account-id
      uses: stormreply/storm-library-for-terraform/.github/actions/get-repository-variable@main
      with:
        repository: stormreply/storm-library-for-terraform
        token: ${{ steps.app-token.outputs.token}}
        variable: ACCOUNT_ID

    - name: Get region
      id: get-region
      uses: stormreply/storm-library-for-terraform/.github/actions/get-repository-variable@main
      with:
        repository: stormreply/storm-library-for-terraform
        token: ${{ steps.app-token.outputs.token}}
        variable: REGION

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up access token
      shell: bash
      run: |
        TOKEN=${{ steps.app-token.outputs.token}}
        git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "https://github.com/"

    - name: Download providers.tf
      shell: bash
      run: |
        TOKEN=${{ steps.app-token.outputs.token }}
        curl \
          -H "Accept: application/vnd.github.raw" \
          -o providers.tf \
          https://x-access-token:$TOKEN@api.github.com/repos/stormreply/storm-library-for-terraform/contents/providers.tf \
        2> /dev/null

    - name: Download backend.tf
      shell: bash
      run: |
        TOKEN=${{ steps.app-token.outputs.token }}
        curl \
          -H "Accept: application/vnd.github.raw" \
          -o backend.tf \
          https://x-access-token:$TOKEN@api.github.com/repos/stormreply/storm-library-for-terraform/contents/backend.tf \
        2> /dev/null

    - name: Get Storm Library catalog item
      shell: bash
      id: catalog-item
      run: |
        TOKEN=${{ steps.app-token.outputs.token }}
        curl \
          -H "Accept: application/vnd.github.raw" \
          -o catalog.yaml \
          https://x-access-token:$TOKEN@api.github.com/repos/stormreply/storm-library-for-terraform/contents/catalog.yaml \
        2> /dev/null
        repository=${{ github.repository }}
        repo=${repository##*/}
        yq '.catalog["'${repo}'"]' catalog.yaml > catalog_item.yaml
        rm catalog.yaml

    - name: Get bucket name
      id: get-bucket-name
      uses: stormreply/storm-library-for-terraform/.github/actions/get-bucket-name@main
      with:
        account_id: ${{ steps.get-account-id.outputs.value}}

    - name: Get deployment name
      id: get-deployment-name
      uses: stormreply/storm-library-for-terraform/.github/actions/get-deployment-name@main
      with:
        environment: ${{ inputs.environment }}

    - name: Get state file
      id: get-state-file
      uses: stormreply/storm-library-for-terraform/.github/actions/get-state-file@main
      with:
        deployment_name: ${{ steps.get-deployment-name.outputs.name }}

    - name: Create deployment variables
      shell: bash
      run: |
        repository=${{ github.repository }}
        repo=${repository##*/}
        deployment_name=${{ steps.get-deployment-name.outputs.name }}

        cat << EOF >> github.tfvars
        deployment = {
          actor       = "${{ github.actor }}"
          environment = "${{ inputs.environment }}"
          name        = "${deployment_name}"
          ref         = "${{ github.ref }}"
          ref_name    = "${{ github.ref_name }}"
          repo        = "${repo}"
          repository  = "${{ github.repository }}"
          sha         = "${{ github.sha }}"
          time        = "$(date)"
        }
        EOF

        cat github.tfvars

    - name: AWS configure
      uses: stormreply/storm-library-for-terraform/.github/actions/aws-configure@main
      with:
        account_id: ${{ steps.get-account-id.outputs.value }}
        region: ${{ steps.get-region.outputs.value }}
        backend_role: slt-0-storm-library-for-terraform-backend
        deployment_role: slt-0-storm-library-for-terraform-deployment
        use_oidc: ${{ inputs.use_oidc }}