name: Terraform apply

runs:
  using: composite
  steps:

    - name: Download tfplan
      uses: actions/download-artifact@v4
      with:
        name: tfplan

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init with S3 backend
      shell: bash
      run: |
        terraform init \
          -backend-config="bucket=${{ env.BACKEND_BUCKET }}" \
          -backend-config="profile=backend" \
          -backend-config="key=${{ github.repository }}/${{ env.STATE_FILE }}" \
          -backend-config="region=${{ env.BACKEND_REGION }}" \
          -backend-config="use_lockfile=true"

    - name: Terraform apply
      shell: bash
      run: |
        # terraform apply
        unset AWS_SECRET_ACCESS_KEY
        unset AWS_SESSION_TOKEN
        unset AWS_ACCESS_KEY_ID

        export AWS_PROFILE=deployment
        echo "AWS_PROFILE=deployment" >> $GITHUB_ENV

        terraform version
        terraform apply \
          -input=false \
          -auto-approve \
          tfplan

    - name: Check for artifact
      shell: bash
      run: |
        # check for artifact
        set +e
        artifact=$(terraform output -raw artifact 2> /dev/null)
        if [ $? -eq 0 ] ; then
          echo "ARTIFACT: [$artifact]"
          echo "ARTIFACT=${artifact}" >> $GITHUB_ENV
        fi
        set -e

    - name: Upload artifact
      if: env.ARTIFACT != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT }}
        path: ${{ env.ARTIFACT }}
