name: Scan code

runs:
  using: composite
  steps:

    - name: checkout code
      uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout@main

    - name: run pre-commit
      uses: stormreply/storm-library-for-terraform/.github/actions/scan/pre-commit@main
      id: pre-commit
