name: Init

inputs:
  access_domain:
    required: true
  access_role:
    required: true
  access_token:
    required: true
  backend_account:
    required: true
  backend_bucket:
    required: true
  backend_region:
    required: true
  deployment_account:
    required: true
  deployment_region:
    required: true
  oidc_principal:
    required: true
  repository:
    required: true
  token:
    required: true

runs:
  using: composite
  steps:

    - name: set AWS backend credentials
      uses: stormreply/storm-library-for-terraform/.github/actions/set/aws/backend/credentials@main
      with:
        access_role: ${{ env.ACCESS_ROLE }}
        access_token: ${{ needs.sso.outputs.access_token }}
        backend_account: ${{ env.BACKEND_ACCOUNT }}
        backend_region: ${{ env.BACKEND_REGION }}

    - name: create AWS backend bucket
      uses: stormreply/storm-library-for-terraform/.github/actions/set/aws/backend/bucket@main
      with:
        backend_bucket: ${{ env.BACKEND_BUCKET }}
        backend_region: ${{ env.BACKEND_REGION }}

    - name: save AWS access vars in ${{github.repository}}.vars
      uses: stormreply/storm-library-for-terraform/.github/actions/set/vars/aws-access@main
      with:
        access_domain: ${{ env.ACCESS_DOMAIN }}
        access_role: ${{ env.ACCESS_ROLE }}
        backend_account: ${{ env.BACKEND_ACCOUNT }}
        backend_region: ${{ env.BACKEND_REGION }}
        oidc_principal: ${{ env.OIDC_PRINCIPAL }}
        repository: ${{ github.repository }}
        token: ${{ env.TOKEN }}

    - name: save AWS backend vars in ${{github.repository}}.vars
      uses: stormreply/storm-library-for-terraform/.github/actions/set/vars/aws-backend@main
      with:
        backend_account: ${{ env.BACKEND_ACCOUNT }}
        backend_region: ${{ env.BACKEND_REGION }}
        repository: ${{ github.repository }}
        token: ${{ env.TOKEN }}

    - name: save AWS deployment vars in ${{github.repository}}.vars
      uses: stormreply/storm-library-for-terraform/.github/actions/set/vars/aws-deployment@main
      with:
        deployment_account: ${{ env.DEPLOYMENT_ACCOUNT }}
        deployment_region: ${{ env.DEPLOYMENT_REGION }}
        repository: ${{ github.repository }}
        token: ${{ env.TOKEN }}
