name: Init

inputs:
  access_token:
    required: true
  repository:
    required: true

runs:
  using: composite
  steps:

    - name: set backend credentials
      uses: stormreply/storm-library-for-terraform/.github/actions/init/set-backend-credentials@main
      with:
        access_token: ${{ inputs.access_token }}

    - name: create backend bucket
      uses: stormreply/storm-library-for-terraform/.github/actions/init/create-backend-bucket@main

    - name: save AWS access vars in ${{github.repository}}.vars
      uses: stormreply/storm-library-for-terraform/.github/actions/init/save-aws-access-vars@main
      with:
        repository: ${{ github.repository }}

    - name: save AWS backend vars in ${{github.repository}}.vars
      uses: stormreply/storm-library-for-terraform/.github/actions/set/vars/aws-backend@main
      with:
        repository: ${{ github.repository }}

    - name: save AWS deployment vars in ${{github.repository}}.vars
      uses: stormreply/storm-library-for-terraform/.github/actions/set/vars/aws-deployment@main
      with:
        repository: ${{ github.repository }}
