name: Get bucket name

inputs:
  access_domain:
    required: true
  access_role:
    required: true
    default: AdministratorAccess
  backend_account:
    required: true
  backend_region:
    required: true
    default: eu-central-1
  github_principal:
    required: true

outputs:
  access_domain:
    value: ${{ steps.get-vars.outputs.access_domain }}
  access_role:
    value: ${{ steps.get-vars.outputs.access_role }}
  backend_account:
    value: ${{ steps.get-vars.outputs.backend_account }}
  backend_region:
    value: ${{ steps.get-vars.outputs.backend_region }}
  github_principal:
    value: ${{ steps.get-vars.outputs.github_principal }}

runs:
  using: composite
  steps:
    - name: Get vars
      id: get-vars
      shell: bash
      run: |
        function check() {
          key=$1
          val=$2
          if [ -n "$val" ] ; then
            echo "$key=$val" | tee -a $GITHUB_OUTPUT
          else
            echo "ERROR: $key is empty. exiting."
            exit 1
          fi
        }
        check access_domain    "${{ inputs.access_domain }}"
        check access_role      "${{ inputs.access_role }}"
        check backend_account  "${{ inputs.backend_account }}"
        check backend_region   "${{ inputs.backend_region }}"
        check github_principal "${{ inputs.github_principal }}"