name: Apply

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      lifetime:
        type: string
        required: false
        default: 1 hour
      delay:
        type: string
        required: false
        default: ""
      environment:
        type: string
        required: false
        default: ""
      var_file:
        type: string
        required: false
        default: ""
    secrets:
      STORM_LIBRARY_FOR_TERRAFORM:
        required: false
      TERRAFORM_PRIVATE_KEY:
        required: false

jobs:

  schedule:
    if: inputs.delay != ''
    runs-on: ubuntu-latest
    steps:

      - name: set environment
        id: set-environment
        uses: stormreply/storm-library-for-terraform/.github/actions/set-environment@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          json: "${{ toJson(vars) }}"
          # TODO: yaml: environment?

      - name: set backend profile in AWS config
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout/set-backend-profile@main

      - name: schedule apply
        uses: stormreply/storm-library-for-terraform/.github/actions/scheduler/schedule@main
        with:
          action: apply
          lifetime: ${{ inputs.lifetime }}
          delay: ${{ inputs.delay }}

  check:
    runs-on: ubuntu-latest
    steps:

      - name: set environment
        id: set-environment
        uses: stormreply/storm-library-for-terraform/.github/actions/set-environment@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          json: "${{ toJson(vars) }}"
          # TODO: yaml: environment?

      - name: scan
        uses: stormreply/storm-library-for-terraform/.github/actions/scan@main

  plan:
    if: inputs.delay == ''
    runs-on: ubuntu-latest
    steps:

      - name: set environment
        id: set-environment
        uses: stormreply/storm-library-for-terraform/.github/actions/set-environment@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          json: "${{ toJson(vars) }}"

      - name: plan
        uses: stormreply/storm-library-for-terraform/.github/actions/plan@main
        with:
          var_file: ${{ inputs.var_file }}

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:

      - name: set environment
        id: set-environment
        uses: stormreply/storm-library-for-terraform/.github/actions/set-environment@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          json: "${{ toJson(vars) }}"
          # TODO: yaml: environment?

      - name: apply
        uses: stormreply/storm-library-for-terraform/.github/actions/apply@main
        with:
          environment: ${{ inputs.environment || github.actor }}

      - name: unschedule apply
        uses: stormreply/storm-library-for-terraform/.github/actions/scheduler/unschedule@main
        with:
          action: apply
        continue-on-error: true

      - name: schedule destroy
        uses: stormreply/storm-library-for-terraform/.github/actions/scheduler/schedule@main
        with:
          action: destroy
          delay: ${{ inputs.lifetime }}
          environment: ${{ inputs.environment || github.actor }}
