name: Apply

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      account_id:
        type: string
        required: true
        default: 123456789012
      environment:
        type: string
        required: true
        default: prod
      expires_after:
        type: string
        required: false
        default: "1 day"
      region:
        type: string
        required: true
        default: eu-central-1
      tfvars:
        type: string
        required: false
        default: ""

jobs:

  plan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare repository
        uses: stormreply/terraform-workflow-controller/.github/actions/prepare-repository@main
        id: prepare-repository
        with:
          environment: ${{ inputs.environment }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Setup roles
        uses: stormreply/terraform-workflow-controller/.github/actions/setup-roles@main
        with:
          account_id: ${{ inputs.account_id }}
          region: ${{ inputs.region }}

      - name: Terraform plan
        uses: stormreply/terraform-workflow-controller/.github/actions/terraform-plan@main
        with:
          environment: ${{ inputs.environment }}
          region: ${{ inputs.region }}
          tfvars: $${{ inputs.tfvars }}

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Prepare repository
        uses: stormreply/terraform-workflow-controller/.github/actions/prepare-repository@main
        id: prepare-repository
        with:
          environment: ${{ inputs.environment }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Setup roles
        uses: stormreply/terraform-workflow-controller/.github/actions/setup-roles@main
        with:
          account_id: ${{ inputs.account_id }}
          region: ${{ inputs.region }}

      - name: Terraform apply
        uses: stormreply/terraform-workflow-controller/.github/actions/terraform-apply@main
        with:
          environment: ${{ inputs.environment }}
          region: ${{ inputs.region }}
          tfvars: $${{ inputs.tfvars }}

      - name: Unregister old deployments
        uses: stormreply/terraform-workflow-controller/.github/actions/unregister@main
        with:
          account_id: ${{ inputs.account_id }}
          environment: ${{ inputs.environment }}
          region: ${{ inputs.region }}

      - name: Register new deployment
        uses: stormreply/terraform-workflow-controller/.github/actions/register@main
        with:
          account_id: ${{ inputs.account_id }}
          environment: ${{ inputs.environment }}
          expires_after: ${{ inputs.expires_after }}
          region: ${{ inputs.region }}