name: Apply

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: ""
      expires_after:
        type: string
        required: false
        default: "1 day"
      region:
        type: string
        required: true
        default: eu-central-1
      var_file:
        type: string
        required: false
        default: ""

jobs:

  plan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        uses: stormreply/storm-library-for-terraform/.github/actions/prepare@main
        id: prepare
        with:
          environment: ${{ inputs.environment }}
          region: ${{ inputs.region }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Terraform plan
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform-plan@main
        with:
          bucket: ${{ steps.prepare.outputs.bucket }}
          region: ${{ inputs.region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: ${{ inputs.var_file}}

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Prepare
        uses: stormreply/storm-library-for-terraform/.github/actions/prepare@main
        id: prepare
        with:
          environment: ${{ inputs.environment }}
          region: ${{ inputs.region }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Terraform apply
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform-apply@main
        with:
          bucket: ${{ steps.prepare.outputs.bucket }}
          region: ${{ inputs.region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: ${{ inputs.var_file}}

      - name: Unregister old deployments
        uses: stormreply/storm-library-for-terraform/.github/actions/unregister@main
        with:
          account_id: ${{ steps.prepare.outputs.account_id }}
          environment: ${{ inputs.environment }}
          region: ${{ inputs.region }}
        continue-on-error: true

      - name: Register new deployment
        uses: stormreply/storm-library-for-terraform/.github/actions/register@main
        with:
          account_id: ${{ steps.prepare.outputs.account_id }}
          environment: ${{ inputs.environment }}
          expires_after: ${{ inputs.expires_after }}
          region: ${{ inputs.region }}