name: Apply

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: ""
      after:
        type: string
        required: false
        default: ""
      ttl:
        type: string
        required: false
        default: 1 day
      var_file:
        type: string
        required: false
        default: ""

jobs:

  queue:
    if: inputs.after != ''
    runs-on: ubuntu-latest
    steps:

      - name: Prepare
        uses: stormreply/storm-library-for-terraform/.github/actions/prepare@main
        id: prepare
        with:
          environment: ${{ inputs.environment }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Register apply
        uses: stormreply/storm-library-for-terraform/.github/actions/register@main
        with:
          account_id: ${{ steps.prepare.outputs.account_id }}
          action: apply
          after: ${{ inputs.after }}
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          deployment_name: ${{ steps.prepare.outputs.deployment_name }}
          deployment_region: ${{ steps.prepare.outputs.deployment_region }}


  check:
    if: inputs.after == ''
    runs-on: ubuntu-latest
    steps:

      - name: Check Code
        uses: stormreply/storm-library-for-terraform/.github/actions/check-code@main
        id: check-code

  plan:
    if: inputs.after == ''
    runs-on: ubuntu-latest
    steps:

      - name: Prepare
        uses: stormreply/storm-library-for-terraform/.github/actions/prepare@main
        id: prepare
        with:
          environment: ${{ inputs.environment }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Terraform plan
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/plan@main
        with:
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          backend_region: ${{ steps.prepare.outputs.backend_region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: ${{ inputs.var_file}}

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Prepare
        uses: stormreply/storm-library-for-terraform/.github/actions/prepare@main
        id: prepare
        with:
          environment: ${{ inputs.environment }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Terraform apply
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/apply@main
        with:
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          backend_region: ${{ steps.prepare.outputs.backend_region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: ${{ inputs.var_file}}

      - name: Unregister all actions
        uses: stormreply/storm-library-for-terraform/.github/actions/unregister@main
        with:
          account_id: ${{ steps.prepare.outputs.account_id }}
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          deployment_name: ${{ steps.prepare.outputs.deployment_name }}
          deployment_region: ${{ steps.prepare.outputs.deployment_region }}
        continue-on-error: true

      - name: Register destroy
        uses: stormreply/storm-library-for-terraform/.github/actions/register@main
        with:
          account_id: ${{ steps.prepare.outputs.account_id }}
          action: destroy
          after: ${{ inputs.ttl }}
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          deployment_name: ${{ steps.prepare.outputs.deployment_name }}
          deployment_region: ${{ steps.prepare.outputs.deployment_region }}
