name: Auto Destroy

permissions:
  contents: read
  id-token: write

on:
  schedule:
    - cron: "17 */4 * * *"  # run once every 4 hours
    # - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  auto-destroy:
    runs-on: ubuntu-latest
    steps:

      - name: Time
        shell: bash
        run: date

      - name: Setup
        id: setup
        uses: stormreply/storm-library-for-terraform/.github/actions/setup@main
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          app_id: ${{ vars.TERRAFORM_APP_ID }}
          private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: gh auth login
        # we need gh auth in order to run gh workflow in batch destroy
        run: echo "${{ steps.setup.outputs.token }}" | gh auth login --with-token

      - name: Set backend profile in AWS config
        # we need to assume role in order to aws s3api in batch destroy
        uses: stormreply/storm-library-for-terraform/.github/actions/set/backend-profile@main
        with:
          account_id: ${{ steps.setup.outputs.account_id }}
          backend_region: ${{ steps.setup.outputs.backend_region }}
          backend_role: slt-0-storm-library-for-terraform-backend

      - name: Batch destroy
        uses: stormreply/storm-library-for-terraform/.github/actions/batch-destroy@main
        with:
          backend_bucket: ${{ steps.setup.outputs.backend_bucket }}
