name: Auto Destroy

permissions:
  contents: read
  id-token: write

on:
  schedule:
    - cron: "17 */4 * * *"  # run once every 4 hours
    # - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  auto-destroy:
    runs-on: ubuntu-latest
    steps:

      - name: Get basic setup
        id: get-basic-setup
        uses: stormreply/storm-library-for-terraform/.github/actions/get-basic-setup@main
        with:
          app_id: ${{ vars.TERRAFORM_APP_ID }}
          private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: gh auth login
        # we need gh auth in order to run gh workflow in batch destroy
        run: echo "${{ steps.get-basic-setup.outputs.token }}" | gh auth login --with-token

      - name: AWS configure
        # we need to assume role in order to aws s3api in batch destroy
        uses: stormreply/storm-library-for-terraform/.github/actions/aws-configure@main
        with:
          account_id: ${{ steps.get-basic-setup.outputs.account_id }}
          region: ${{ steps.get-basic-setup.outputs.region }}
          backend_role: slt-0-storm-library-for-terraform-backend
          deployment_role: slt-0-storm-library-for-terraform-deployment

      - name: Batch destroy
        uses: stormreply/storm-library-for-terraform/.github/actions/batch-destroy@main
        with:
          bucket: ${{ steps.get-basic-setup.outputs.bucket }}
