name: Cleanup

permissions:
  contents: read
  id-token: write

on:
  schedule:
    - cron: "17 */4 * * *"  # run once every 4 hours
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:

      - name: Create app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.TERRAFORM_APP_ID }}
          private-key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Authenticate
        run: echo "${{ steps.app-token.outputs.token }}" | gh auth login --with-token

      - name: Setup roles
        uses: stormreply/terraform-workflow-controller/.github/actions/setup-roles@main
        with:
          # TODO:
          account_id: 123456789012
          region: eu-central-1

      - name: Check expired
        shell: bash
        run: |
          expiries=$(
            aws s3api list-objects \
              --bucket storm-github-terraform-backend \
              --prefix expiries \
            | jq -r '.Contents[].Key'
          )
          for e in $expiries ; do
            file=${e##*/} ; f=${file}
            date=${f%%-*} ; f=${f##$date-}
            time=${f%%-*} ; f=${f##$time-}
            account_id=${f%%-*} ; f=${f##$account_id-}
            region=${f%-${f#*-*-*-}} ; f=${f##$region-}
            storm=${f%%-*} ; f=${f##$storm-}
            repo=${f%-*}
            environment=${f##$repo-}
            time="${time:0:2}:${time:2:2}:${time:4:2}"
            expiry=$(date -d "${date} ${time}" +"%s")
            now=$(date -d now +"%s")
            echo -n "checking ${file}... "
            if [ ${expiry} -lt ${now} ] ; then
              echo "EXPIRED"
              gh workflow run plan.yaml \
                --repo "stormreply/${repo}" \
              & # TODO: handle "stormreply"
            else
              echo "ok"
            fi
          done