name: Cleanup

permissions: write-all

on:
  schedule:
    - cron: "*/5 * * * *"  # run every 5 minutes
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:

      # - uses: actions/create-github-app-token@v1
      #   id: app-token
      #   with:
      #     app-id: ${{ vars.TERRAFORM_APP_ID }}
      #     private-key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
      #     owner: ${{ github.repository_owner }}

      - name: Setup roles
        uses: stormreply/terraform-workflow-controller/.github/actions/setup-roles@main
        with:
          # TODO:
          account_id: 123456789012
          region: eu-central-1

      - name: Check expired
        shell: bash
        run: |
          expiries=$(
            aws s3api list-objects \
              --bucket storm-github-terraform-backend \
              --prefix expiries \
            | jq -r '.Contents[].Key'
          )
          for e in $expiries ; do
            f=${e##*/}
            date=${f%%-*} ; f=${f##$date-}
            time=${f%%-*} ; f=${f##$time-}
            account_id=${f%%-*} ; f=${f##$account_id-}
            region=${f%-${f#*-*-*-}} ; f=${f##$region-}
            storm=${f%%-*} ; f=${f##$storm-}
            repo=${f%-*}
            environment=${f##$repo-}
            time="${time:0:2}:${time:2:2}:${time:4:2}"
            expiry=$(date -d "${date} ${time}" +"%s")
            now=$(date -d now +"%s")
            if [ ${expiry} -lt ${now} ] ; then
              echo "${storm}-${repo}-${environment} EXPIRED!"
            else
              echo "${storm}-${repo}-${environment} STILL VALID!"
            fi
          done