name: Init

on:
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      access_domain:
        required: true
        default: storm-unity
      backend_account:
        required: true
        default: 123456789012
      backend_region:
        required: true
        default: eu-central-1

permissions:
  actions: write
  contents: read

jobs:

  sso:
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.sso.outputs.access_token }}
    steps:

      - name: Single sign on
        id: sso
        uses: stormreply/storm-library-for-terraform/.github/actions/init/single-sign-on@main
        with:
          access_domain: ${{ inputs.access_domain }}
          backend_region: ${{ inputs.backend_region }}

  init:
    needs: sso
    runs-on: ubuntu-latest
    steps:

      - name: Get role credentials
        uses: stormreply/storm-library-for-terraform/.github/actions/init/get-role-credentials@main
        with:
          access_token: ${{ needs.sso.outputs.access_token }}
          backend_account: ${{ inputs.backend_account }}
          backend_region: ${{ inputs.backend_region }}
          role_name: AdministratorAccess

      - name: Prepare
        uses: stormreply/storm-library-for-terraform/.github/actions/prepare@main
        id: prepare
        with:
          backend_account: ${{ inputs.backend_account }}
          backend_region: ${{ inputs.backend_region }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          # token: ${{ secrets.GITHUB_TOKEN }}
          use_oidc: false

      - name: Check SLT backend bucket
        shell: bash
        run: |
          backend_bucket=${{ steps.prepare.outputs.backend_bucket }}
          aws s3api create-bucket \
            --bucket ${backend_bucket} \
            --region ${{ inputs.backend_region }} \
            --create-bucket-configuration LocationConstraint=${{ inputs.backend_region }} \
          || true
          cat << EOF >> init.tfvars
          backend_bucket = "${backend_bucket}"
          EOF

      - name: Terraform plan
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/plan@main
        with:
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          backend_region: ${{ inputs.backend_region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: init.tfvars

      - name: Terraform apply
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/apply@main
        with:
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          backend_region: ${{ inputs.backend_region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: init.tfvars

      - name: Save backend account
        uses: stormreply/storm-library-for-terraform/.github/actions/set/variable@main
        with:
          repository: ${{ github.repository }}
          token: ${{ steps.prepare.outputs.app_token }}
          value: ${{ inputs.backend_account }}
          variable: BACKEND_ACCOUNT

      - name: Save backend region
        uses: stormreply/storm-library-for-terraform/.github/actions/set/variable@main
        with:
          repository: ${{ github.repository }}
          token: ${{ steps.prepare.outputs.app_token }}
          value: ${{ inputs.backend_region }}
          variable: BACKEND_REGION
