name: Init

on:
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      access_domain:
        description: "Access domain"
        type: string
      access_role:
        description: "Access role"
        type: string
      backend_account:
        description: "Backend account"
        type: string
      backend_region:
        description: "Backend region"
        type: string
      oidc_principal:
        description: "OIDC principal"
        type: string

permissions:
  actions: write
  contents: read

jobs:

  sso:
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.sso.outputs.access_token }}
    steps:

      # TODO: reduce to get-access-domain, get-backend-region
      - name: get vars
        id: get-vars
        uses: stormreply/storm-library-for-terraform/.github/actions/get/vars@main
        with:
          access_domain: ${{ inputs.access_domain || vars.ACCESS_DOMAIN }}
          access_role: ${{ inputs.access_role || vars.ACCESS_ROLE }}
          backend_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }}
          backend_region: ${{ inputs.backend_region || vars.BACKEND_REGION }}
          deployment_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }} # TODO:
          deployment_region: ${{ inputs.backend_region || vars.BACKEND_REGION }} # TODO:
          environment: ${{ github.repository_owner }}
          oidc_principal: ${{ inputs.oidc_principal || vars.OIDC_PRINCIPAL || github.repository_owner }}
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: single sign on
        id: sso
        uses: stormreply/storm-library-for-terraform/.github/actions/sso@main
        with:
          access_domain: ${{ steps.get-vars.outputs.access_domain }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}

  oidc:
    needs: sso
    runs-on: ubuntu-latest
    steps:

      - name: get vars
        id: get-vars
        uses: stormreply/storm-library-for-terraform/.github/actions/get/vars@main
        with:
          access_domain: ${{ inputs.access_domain || vars.ACCESS_DOMAIN }}
          access_role: ${{ inputs.access_role || vars.ACCESS_ROLE }}
          backend_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }}
          backend_region: ${{ inputs.backend_region || vars.BACKEND_REGION }}
          deployment_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }} # TODO:
          deployment_region: ${{ inputs.backend_region || vars.BACKEND_REGION }} # TODO:
          environment: ${{ github.repository_owner }}
          oidc_principal: ${{ inputs.oidc_principal || vars.OIDC_PRINCIPAL || github.repository_owner }}
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: set AWS credentials
        uses: stormreply/storm-library-for-terraform/.github/actions/set/aws/credentials@main
        with:
          access_role: ${{ steps.get-vars.outputs.access_role }}
          access_token: ${{ needs.sso.outputs.access_token }}
          backend_account: ${{ steps.get-vars.outputs.backend_account }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}

      - name: prepare
        id: prepare
        uses: stormreply/storm-library-for-terraform/.github/actions/prepare@main
        with:
          backend_account: ${{ steps.get-vars.outputs.backend_account }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}
          deployment_name: ${{ steps.get-vars.outputs.deployment_name }}
          environment: ${{ inputs.environment }} # TODO: get from get-vars
          token: ${{ steps.get-vars.outputs.token }}
          use_oidc: false

      - name: set backend
        uses: stormreply/storm-library-for-terraform/.github/actions/set/backend@main
        with:
          backend_account: ${{ steps.get-vars.outputs.backend_account }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}
          repository: ${{ github.repository }}
          token: ${{ steps.get-vars.outputs.token }}

      - name: set AWS config
        uses: stormreply/storm-library-for-terraform/.github/actions/set/aws/config@main
        with:
          access_domain: ${{ steps.get-vars.outputs.access_domain }}
          access_role: ${{ steps.get-vars.outputs.access_role }}
          access_token: ${{ needs.sso.outputs.access_token }}
          backend_account: ${{ steps.get-vars.outputs.backend_account }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}
          oidc_principal: ${{ steps.get-vars.outputs.oidc_principal }}
          repository: ${{ github.repository }}
          token: ${{ steps.get-vars.outputs.token }}

      - name: set tfvars
        uses: stormreply/storm-library-for-terraform/.github/actions/set/init-tfvars@main
        with:
          backend_bucket: ${{ steps.get-vars.outputs.backend_bucket }}
          oidc_principal: ${{ steps.get-vars.outputs.oidc_principal }}

      - name: Terraform plan
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/plan@main
        with:
          backend_bucket: ${{ steps.get-vars.outputs.backend_bucket }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}
          state_file: ${{ steps.get-vars.outputs.state_file }}
          var_file: oidc.tfvars

      - name: Terraform apply
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/apply@main
        with:
          backend_bucket: ${{ steps.get-vars.outputs.backend_bucket }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}
          state_file: ${{ steps.get-vars.outputs.state_file }}
          var_file: oidc.tfvars
