name: Init

on:
  workflow_dispatch:
    inputs:
      access_domain:
        required: true
        default: storm-unity
      account_id:
        required: true
        default: 123456789012
      region:
        required: false
        default: eu-central-1

jobs:

  sso:
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.sso.outputs.access_token }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Single sign on
        id: sso
        uses: stormreply/terraform-workflow-controller/.github/actions/single-sign-on@main
        with:
          access_domain: ${{ inputs.access_domain }}
          region: ${{ inputs.region }}

  init:
    needs: sso
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get role credentials
        uses: stormreply/terraform-workflow-controller/.github/actions/get-role-credentials@main
        with:
          access_token: ${{ needs.sso.outputs.access_token }}
          account_id: ${{ inputs.account_id }}
          region: ${{ inputs.region }}
          role_name: AdministratorAccess

      - name: Prepare
        uses: stormreply/terraform-workflow-controller/.github/actions/prepare@main
        id: prepare
        with:
          region: $${{ inputs.region }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          use_oidc: false

      - name: Check SLT bucket
        shell: bash
        run: |
          BUCKET="storm-library-for-terraform-${{ inputs.account_id }}"
          aws s3api create-bucket \
            --bucket $BUCKET \
            --region ${{ inputs.region }} \
            --create-bucket-configuration LocationConstraint=${{ inputs.region }} \
          || true
          cat << EOF >> init.tfvars
          bucket = "${BUCKET}"
          EOF

      - name: Terraform plan
        uses: stormreply/terraform-workflow-controller/.github/actions/terraform-plan@main
        with:
          bucket: storm-library-for-terraform-${{ inputs.account_id }}
          region: ${{ inputs.region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: init.tfvars

      - name: Terraform apply
        uses: stormreply/terraform-workflow-controller/.github/actions/terraform-apply@main
        with:
          bucket: storm-library-for-terraform-${{ inputs.account_id }}
          region: ${{ inputs.region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: init.tfvars