name: Monthly Build Test

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:

  build-test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # TODO: check if necessary
      contents: read

    strategy:
      matrix:
        repo:
          - "stormreply/terraform-build-controller"

    steps:

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.TERRAFORM_APP_ID }}
          private-key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Authenticate GitHub CLI
        run: echo "${{ steps.app-token.outputs.token }}" | gh auth login --with-token

    # steps:
    #   - name: Test ${{ matrix.repo }}
    #     uses: stormreply/${{ matrix.repo }}/.github/workflows/test.yaml@main
