name: Monthly Build Test

on:
  # schedule:
  #   - cron: '50 12 1 * *'
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # TODO: check if necessary
      contents: read

    strategy:
      matrix:
        repo:
          - "stormreply/terraform-build-controller"
          - "stormreply/sakila-mysql-rds"

    steps:

      - name: Create app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.TERRAFORM_APP_ID }}
          private-key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Authenticate
        run: echo "${{ steps.app-token.outputs.token }}" | gh auth login --with-token

      - name: Test
        run: |
          gh workflow run plan.yaml --repo ${{ matrix.repo }}
