name: OIDC

on:
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      access_domain:
        description: "Access domain"
        type: string
      access_role:
        description: "Access role"
        type: string
      backend_account:
        description: "Backend account"
        type: string
      backend_region:
        description: "Backend region"
        type: string
      oidc_principal:
        description: "OIDC principal"
        type: string

permissions:
  actions: write
  contents: read

jobs:

  sso:
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.sso.outputs.access_token }}
    steps:

      - name: Get Token
        id: get-token
        uses: stormreply/storm-library-for-terraform/.github/actions/get/token@main
        with:
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      # TODO: reduce to get-access-domain, get-backend-region
      - name: Get Vars
        id: get-vars
        uses: stormreply/storm-library-for-terraform/.github/actions/get/vars@main
        with:
          access_domain: ${{ inputs.access_domain || vars.ACCESS_DOMAIN }}
          access_role: ${{ inputs.access_role || vars.ACCESS_ROLE }}
          backend_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }}
          backend_region: ${{ inputs.backend_region || vars.BACKEND_REGION }}
          deployment_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }} # TODO:
          deployment_region: ${{ inputs.backend_region || vars.BACKEND_REGION }} # TODO:
          environment: ${{ github.repository_owner }}
          oidc_principal: ${{ inputs.oidc_principal || vars.OIDC_PRINCIPAL || github.repository_owner }}
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Single sign on
        id: sso
        uses: stormreply/storm-library-for-terraform/.github/actions/oidc/single-sign-on@main
        with:
          access_domain: ${{ steps.get-vars.outputs.access_domain }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}

  oidc:
    needs: sso
    runs-on: ubuntu-latest
    steps:

      - name: Get Vars
        id: get-vars
        uses: stormreply/storm-library-for-terraform/.github/actions/get/vars@main
        with:
          access_domain: ${{ inputs.access_domain || vars.ACCESS_DOMAIN }}
          access_role: ${{ inputs.access_role || vars.ACCESS_ROLE }}
          backend_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }}
          backend_region: ${{ inputs.backend_region || vars.BACKEND_REGION }}
          deployment_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }} # TODO:
          deployment_region: ${{ inputs.backend_region || vars.BACKEND_REGION }} # TODO:
          environment: ${{ github.repository_owner }}
          oidc_principal: ${{ inputs.oidc_principal || vars.OIDC_PRINCIPAL || github.repository_owner }}
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Set role credentials
        uses: stormreply/storm-library-for-terraform/.github/actions/set/role-credentials@main
        with:
          access_role: ${{ steps.get-vars.outputs.access_role }}
          access_token: ${{ needs.sso.outputs.access_token }}
          backend_account: ${{ steps.get-vars.outputs.backend_account }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}

      - name: Prepare
        id: prepare
        uses: stormreply/storm-library-for-terraform/.github/actions/prepare@main
        with:
          access_domain: ${{ steps.get-vars.outputs.access_domain }}
          access_role: ${{ steps.get-vars.outputs.access_role }}
          backend_account: ${{ steps.get-vars.outputs.backend_account }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}
          deployment_account: ${{ steps.get-vars.outputs.backend_account }} # TODO:
          deployment_region: ${{ steps.get-vars.outputs.backend_region }} # TODO:
          environment: ${{ inputs.environment }} # TODO: get from get-vars
          oidc_principal: ${{ steps.get-vars.outputs.oidc_principal }}
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          use_oidc: false

      - name: Set backend bucket
        id: set-backend-bucket
        uses: stormreply/storm-library-for-terraform/.github/actions/set/backend-bucket@main
        with:
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}

      - name: Set access domain
        uses: stormreply/storm-library-for-terraform/.github/actions/set/variable@main
        with:
          repository: ${{ github.repository }}
          token: ${{ steps.prepare.outputs.token }}
          value: ${{ steps.get-vars.outputs.access_domain }}
          variable: ACCESS_DOMAIN

      - name: Set access role
        uses: stormreply/storm-library-for-terraform/.github/actions/set/variable@main
        with:
          repository: ${{ github.repository }}
          token: ${{ steps.prepare.outputs.token }}
          value: ${{ steps.get-vars.outputs.access_role }}
          variable: ACCESS_ROLE

      - name: Set backend account
        uses: stormreply/storm-library-for-terraform/.github/actions/set/variable@main
        with:
          repository: ${{ github.repository }}
          token: ${{ steps.prepare.outputs.token }}
          value: ${{ steps.get-vars.outputs.backend_account }}
          variable: BACKEND_ACCOUNT

      - name: Set backend region
        uses: stormreply/storm-library-for-terraform/.github/actions/set/variable@main
        with:
          repository: ${{ github.repository }}
          token: ${{ steps.prepare.outputs.token }}
          value: ${{ steps.get-vars.outputs.backend_region }}
          variable: BACKEND_REGION

      - name: Set OIDC principal
        uses: stormreply/storm-library-for-terraform/.github/actions/set/oidc-principal@main
        with:
          oidc_principal: ${{ steps.get-vars.outputs.oidc_principal }}
          repository: ${{ github.repository }}
          token: ${{ steps.prepare.outputs.token }}

      - name: Terraform plan
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/plan@main
        with:
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: oidc.tfvars

      - name: Terraform apply
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/apply@main
        with:
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          backend_region: ${{ steps.get-vars.outputs.backend_region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: oidc.tfvars
