name: Plan

permissions: write-all

on:
  workflow_call:
    inputs:
      account_id:
        type: string
        required: true
        default: 123456789012
      environment:
        type: string
        required: true
        default: prod
      region:
        type: string
        required: true
        default: eu-central-1
      release:
        type: string
        required: false
        default: prod
      tfvars:
        type: string
        required: false
        default: ""

jobs:

  plan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare repository
        uses: stormreply/terraform-workflow-controller/.github/actions/prepare-repository@main
        id: prepare-repository
        with:
          environment: ${{ inputs.environment }}
          release: ${{ inputs.release }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}


      - name: Setup roles
        uses: stormreply/terraform-workflow-controller/.github/actions/setup-roles@main
        with:
          account_id: ${{ inputs.account_id }}
          region: ${{ inputs.region }}

      - name: Terraform plan
        uses: stormreply/terraform-workflow-controller/.github/actions/terraform-plan@main
        with:
          environment: ${{ inputs.environment }}
          region: ${{ inputs.region }}
          release: ${{ inputs.release }}
          repository: ${{ steps.prepare-repository.outputs.repository }}
          tfvars: $${{ inputs.tfvars }}