name: Plan

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      var_file:
        type: string
        required: false
        default: ""
    secrets:
      STORM_LIBRARY_FOR_TERRAFORM:
        required: false
      TERRAFORM_PRIVATE_KEY:
        required: false

jobs:

  check:
    runs-on: ubuntu-latest
    steps:

      - name: Time
        shell: bash
        run: date

      - name: set environment vars
        id: set-env
        uses: stormreply/storm-library-for-terraform/.github/actions/set/env@main
        with:
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          yaml: |
            backend_account: ${{ vars.BACKEND_ACCOUNT }}
            backend_region: ${{ vars.BACKEND_REGION }}
            environment: ${{ github.actor }}
            terraform_app_id: ${{ vars.TERRAFORM_APP_ID || 'NONE' }}

      - name: scan
        uses: stormreply/storm-library-for-terraform/.github/actions/scan@main

  plan:
    runs-on: ubuntu-latest
    steps:

      - name: set environment vars
        id: set-env
        uses: stormreply/storm-library-for-terraform/.github/actions/set/env@main
        with:
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          yaml: |
            backend_account: ${{ vars.BACKEND_ACCOUNT }}
            backend_region: ${{ vars.BACKEND_REGION }}
            environment: ${{ github.actor }}
            terraform_app_id: ${{ vars.TERRAFORM_APP_ID || 'NONE' }}

      - name: checkout code
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/checkout@main
        with:
          backend_account: ${{ env.BACKEND_ACCOUNT }}
          backend_region: ${{ env.BACKEND_REGION }}
          deployment_name: ${{ env.DEPLOYMENT_NAME }}
          environment: ${{ env.ENVIRONMENT }}
          token: ${{ env.TOKEN }}

      - name: Terraform plan
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/plan@main
        with:
          backend_bucket: ${{ env.BACKEND_BUCKET }}
          backend_region: ${{ env.BACKEND_REGION }}
          state_file: ${{ env.STATE_FILE }}
          var_file: ${{ inputs.var_file }}
