name: Plan

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:

      var_file:
        type: string
        required: false
        default: ""

      # access_domain:
      #   type: string
      #   required: false
      # access_role:
      #   type: string
      #   required: false
      backend_account:
        type: string
        required: false
      backend_region:
        type: string
        required: false
      environment:
        type: string
        required: false
      oidc_principal:
        type: string
        required: false
      # private_access_token:
      #   type: string
      #   required: true
      terraform_app_id:
        type: string
        required: false
      # terraform_private_key:
      #   type: string
      #   required: true


jobs:

  check:
    runs-on: ubuntu-latest
    steps:

      - name: Prepare
        uses: stormreply/storm-library-for-terraform/.github/actions/prepare@main
        id: prepare
        with:
          # access_domain: ${{ inputs.access_domain || vars.ACCESS_DOMAIN }}
          # access_role: ${{ inputs.access_role || vars.ACCESS_ROLE }}
          backend_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }}
          backend_region: ${{ inputs.backend_region || vars.BACKEND_REGION }}
          deployment_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }} # TODO:
          deployment_region: ${{ inputs.backend_region || vars.BACKEND_REGION }} # TODO:
          environment: ${{ github.repository_owner }}
          # oidc_principal: ${{ inputs.oidc_principal || vars.OIDC_PRINCIPAL || github.repository_owner }}
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Check Code
        uses: stormreply/storm-library-for-terraform/.github/actions/check-code@main
        id: check-code
        # with:
        #   token: ${{ steps.prepare.outputs.token }}

  plan:
    runs-on: ubuntu-latest
    steps:

      - name: Prepare
        uses: stormreply/storm-library-for-terraform/.github/actions/prepare@main
        id: prepare
        with:
          # access_domain: ${{ inputs.access_domain || vars.ACCESS_DOMAIN }}
          # access_role: ${{ inputs.access_role || vars.ACCESS_ROLE }}
          backend_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }}
          backend_region: ${{ inputs.backend_region || vars.BACKEND_REGION }}
          deployment_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }} # TODO:
          deployment_region: ${{ inputs.backend_region || vars.BACKEND_REGION }} # TODO:
          environment: ${{ github.repository_owner }}
          # oidc_principal: ${{ inputs.oidc_principal || vars.OIDC_PRINCIPAL || github.repository_owner }}
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Terraform plan
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform/plan@main
        with:
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          backend_region: ${{ steps.prepare.outputs.backend_region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: ${{ inputs.var_file}}
