name: Plan

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      var_file:
        type: string
        required: false
        default: ""
    secrets:
      STORM_LIBRARY_FOR_TERRAFORM:
        required: false
      TERRAFORM_PRIVATE_KEY:
        required: false

jobs:

  check:
    runs-on: ubuntu-latest
    steps:

      - name: Time
        shell: bash
        run: date

      - name: set environment
        id: set-environment
        uses: stormreply/storm-library-for-terraform/.github/actions/set-environment@main
        with:
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          json: "${{ toJson(vars) }}"

      - name: scan
        uses: stormreply/storm-library-for-terraform/.github/actions/scan@main

  plan:
    runs-on: ubuntu-latest
    steps:

      - name: set environment
        id: set-environment
        uses: stormreply/storm-library-for-terraform/.github/actions/set-environment@main
        with:
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          json: "${{ toJson(vars) }}"

      - name: plan
        uses: stormreply/storm-library-for-terraform/.github/actions/plan@main
        with:
          var_file: ${{ inputs.var_file }}
