name: Plan

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: ""
      var_file:
        type: string
        required: false
        default: ""

jobs:

  check:
    runs-on: ubuntu-latest
    steps:

      - name: Check
        uses: stormreply/storm-library-for-terraform/.github/actions/check@main
        id: check

  plan:
    runs-on: ubuntu-latest
    steps:

      - name: Prepare
        uses: stormreply/storm-library-for-terraform/.github/actions/prepare@main
        id: prepare
        with:
          environment: ${{ inputs.environment }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Terraform plan
        uses: stormreply/storm-library-for-terraform/.github/actions/terraform-plan@main
        with:
          backend_bucket: ${{ steps.prepare.outputs.backend_bucket }}
          backend_region: ${{ steps.prepare.outputs.backend_region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: ${{ inputs.var_file}}
