name: Plan

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      account_id:
        type: string
        required: true
        default: 123456789012
      environment:
        type: string
        required: false
        default: ""
      region:
        type: string
        required: true
        default: eu-central-1
      var_file:
        type: string
        required: false
        default: ""

jobs:

  plan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare repository
        uses: stormreply/terraform-workflow-controller/.github/actions/prepare@main
        id: prepare
        with:
          environment: ${{ inputs.environment }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: Setup roles
        uses: stormreply/terraform-workflow-controller/.github/actions/setup-roles@main
        with:
          account_id: ${{ inputs.account_id }}
          region: ${{ inputs.region }}

      - name: Terraform plan
        uses: stormreply/terraform-workflow-controller/.github/actions/terraform-plan@main
        with:
          region: ${{ inputs.region }}
          state_file: ${{ steps.prepare.outputs.state_file }}
          var_file: ${{ inputs.var_file}}
