name: Set backend

# permissions:
#   contents: read
#   actions: write

on:
  workflow_call:
    inputs:

      backend_account:
        type: string
        required: true
      backend_region:
        type: string
        required: true
    secrets:
      STORM_LIBRARY_FOR_TERRAFORM:
        required: false
      TERRAFORM_PRIVATE_KEY:
        required: false

jobs:

  set-backend:
    runs-on: ubuntu-latest
    steps:

      - name: Time
        shell: bash
        run: date

      - name: set environment vars
        id: set-env
        uses: stormreply/storm-library-for-terraform/.github/actions/set/env@main
        with:
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          yaml: |
            backend_account: ${{ inputs.backend_account }}
            backend_region: ${{ inputs.backend_region }}

      - name: save AWS backend vars in ${{github.repository}}.vars
        uses: stormreply/storm-library-for-terraform/.github/actions/set/vars/aws-backend@main
        with:
          backend_account: ${{ env.BACKEND_ACCOUNT }}
          backend_region: ${{ env.BACKEND_REGION }}
          repository: ${{ github.repository }}
          token: ${{ env.TOKEN }}