name: Set backend

permissions:
  read-all

on:
  workflow_call:
    inputs:
      backend_account:
        type: string
        required: true
      backend_region:
        type: string
        required: true
    secrets:
      STORM_LIBRARY_FOR_TERRAFORM:
        required: false
      TERRAFORM_PRIVATE_KEY:
        required: false

jobs:

  set-backend:
    runs-on: ubuntu-latest
    steps:

      - name: Time
        shell: bash
        run: date

      - name: set environment
        id: set-environment
        uses: stormreply/storm-library-for-terraform/.github/actions/set-environment@main
        with:
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: set backend account
        id: set-backend-account
        uses: stormreply/storm-library-for-terraform/.github/actions/init/save-variable@main
        with:
          repository: ${{ github.repository }}
          value: ${{ env.BACKEND_ACCOUNT }}
          variable: BACKEND_ACCOUNT

      - name: set backend region
        id: set-backend-region
        uses: stormreply/storm-library-for-terraform/.github/actions/init/save-variable@main
        with:
          repository: ${{ github.repository }}
          value: ${{ env.BACKEND_REGION }}
          variable: BACKEND_REGION
