name: Show Config

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:

  show:
    runs-on: ubuntu-latest
    steps:

      - name: set environment vars
        id: set-env
        uses: stormreply/storm-library-for-terraform/.github/actions/set/env@main
        with:
          private_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          yaml: |
            access_domain: ${{ vars.ACCESS_DOMAIN }}
            access_role: ${{ vars.ACCESS_ROLE }}
            backend_account: ${{ vars.BACKEND_ACCOUNT }}
            backend_region: ${{ vars.BACKEND_REGION }}
            deployment_account: ${{ vars.DEPLOYMENT_ACCOUNT }}
            deployment_region: ${{ vars.DEPLOYMENT_REGION }}
            environment: ${{ github.actor }}
            oidc_principal: ${{ vars.OIDC_PRINCIPAL || github.actor }}
            terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
