name: Show Config

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:

  show:
    runs-on: ubuntu-latest
    steps:

      - name: set environment
        id: set-environment
        uses: stormreply/storm-library-for-terraform/.github/actions/set-environment@main
        with:
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          json: "${{ toJson(vars) }}"
