name: Show Configuration

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:

  show:
    runs-on: ubuntu-latest
    steps:

      - name: Show current Configuration
        id: show-current-configuration
        uses: stormreply/storm-library-for-terraform/.github/actions/get/configuration@main
        with:
          backend_account: ${{ vars.BACKEND_ACCOUNT }}
          backend_region: ${{ vars.BACKEND_REGION }}
          deployment_account: ${{ vars.DEPLOYMENT_ACCOUNT }}
          deployment_region: ${{ vars.DEPLOYMENT_REGION }}
