name: Token Test

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo token length
        run: echo "${{ secrets.GITHUB_TOKEN }}" | wc -c

      - name: Test API Call
        run: |
          curl -i -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/variables
