name: Register deployment

inputs:
  account_id:
    required: true
  backend_bucket:
    required: true
  deployment_name:
    required: true
  deployment_region:
    required: true
  expires_after:
    required: true

runs:
  using: composite
  steps:

    - name: Register expiry
      shell: bash
      run: |
        account_id=${{ inputs.account_id }}
        backend_bucket=${{ inputs.backend_bucket }}
        deployment_name="${{ inputs.deployment_name }}"
        deployment_region=${{ inputs.deployment_region }}

        expiry=$(date -d "now + ${{ inputs.expires_after}}" +"%Y%m%d-%H%M%S")
        timestamp="${expiry}-${account_id}-${deployment_region}-${deployment_name}"
        touch ${timestamp}
        aws s3 cp ${timestamp} s3://${backend_bucket}/schedule/
        echo "REGISTERED ${timestamp}"
