name: Register deployment

inputs:
  account_id:
    required: true
  environment:
    required: true
  expires_after:
    required: true
  region:
    required: true

runs:
  using: "composite"
  steps:
    - name: Register expiry
      shell: bash
      run: |
        account_id=${{ inputs.account_id }}
        region=${{ inputs.region }}
        repository=${{ github.repository }}
        repo=${repository##*/}
        deployment="storm-${repo}-${{ inputs.environment }}"

        expiry=$(date -d "now + ${{ inputs.expires_after}}" +"%Y%m%d-%H%M%S")
        expiry_file="${expiry}-${account_id}-${region}-${deployment}"
        touch ${expiry_file}
        aws s3 cp ${expiry_file} s3://storm-github-terraform-backend/expiries/  # TODO: take bucket name from vars
        echo "REGISTERED ${expiry_file}"