name: Register deployment

inputs:
  account_id:
    required: true
  environment:
    required: true
  expires_after:
    required: true
  region:
    required: true

runs:
  using: composite
  steps:

    - name: Get bucket name
      id: get-bucket-name
      uses: stormreply/storm-library-for-terraform/.github/actions/get-bucket-name@main
      with:
        account_id: ${{ inputs.account_id }}

    - name: Register expiry
      shell: bash
      run: |
        account_id=${{ inputs.account_id }}
        region=${{ inputs.region }}
        repository=${{ github.repository }}
        repo=${repository##*/}
        deployment="storm-${repo}-${{ inputs.environment }}"

        expiry=$(date -d "now + ${{ inputs.expires_after}}" +"%Y%m%d-%H%M%S")
        timestamp="${expiry}-${account_id}-${region}-${deployment}"
        touch ${timestamp}
        aws s3 cp ${timestamp} s3://${{ steps.get-bucket-name.outputs.bucket }}/schedule/
        echo "REGISTERED ${timestamp}"